(()=>{'use strict';
const C=window.MOL_APP_CONFIG,$=id=>document.getElementById(id),qa=s=>[...document.querySelectorAll(s)];
const P={PAKOWANIE:['Pakowanie','▣','#2f76e8'],KOMPLETACJA:['Kompletacja','⌑','#24a060'],DYZUR:['Dyżur','◷','#7666d8'],ZWROTY:['Zwroty','↩','#dc5260'],BIURO:['Biuro','▤','#a96b24'],PORZADKI_KARTONY:['Porządki – kartony','◇','#ba8619'],PRZYGOTOWANIE_STANOWISKA:['Przygotowanie stanowiska','⌂','#238a89'],MAGAZYN:['Magazyn','▥','#50698c'],PRZERWA:['Przerwa','♨','#7653bd'],INNE:['Inne','•••','#67758b']};
const MIN={PAKOWANIE:'pak_minutes',KOMPLETACJA:'pick_minutes',DYZUR:'duty_minutes',ZWROTY:'returns_minutes',BIURO:'office_minutes',PORZADKI_KARTONY:'cardboard_minutes',PRZYGOTOWANIE_STANOWISKA:'workstation_prep_minutes',MAGAZYN:'warehouse_minutes',PRZERWA:'break_minutes',INNE:'other_minutes'};
const S={token:null,user:null,expires:null,config:null,wd:null,daily:null,monthly:null,alerts:[],team:[],leaderDirectory:[],leaderAlerts:[],active:null,workerView:'home',leaderView:'monitoring',mode:'worker',norm:'daily',modalAlert:null,confirm:null,timers:{}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=k=>`${C.apiBase}/${C.endpoints[k]}`;
const time=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?'—':d.toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'})};
const dur=s=>{s=Math.max(0,Math.floor(+s||0));return[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')};
const mins=v=>{v=Math.max(0,+v||0);const h=Math.floor(v/60),m=Math.round(v%60);return h?`${h} h ${String(m).padStart(2,'0')} min`:`${m} min`};
const pct=v=>v==null||!isFinite(+v)?'—':`${(+v).toFixed((+v)%1?1:0)}%`;
const share=(part,total)=>{part=Math.max(0,+part||0);total=Math.max(0,+total||0);return total>0?`${(part/total*100).toFixed(1)}%`:'—'};
function online(ok){const c=$('connectionState');if(c){c.classList.toggle('offline',!ok);c.innerHTML=`<i></i>${ok?'Online':'Offline'}`}$('offlineBar').hidden=ok}
async function api(k,{method='GET',body=null,query=null,auth=true}={}){let u=url(k);if(query)u+=`?${new URLSearchParams(query)}`;const o={method,headers:{Accept:'application/json',...(auth&&S.token?{Authorization:`Bearer ${S.token}`}:{})},cache:'no-store'};if(body!==null){o.headers['Content-Type']='application/json';o.body=JSON.stringify(body)}let r;try{r=await fetch(u,o);online(true)}catch(e){online(false);throw Object.assign(new Error('NETWORK'),{status:0})}let d={};try{d=await r.json()}catch(e){throw Object.assign(new Error(`HTTP_${r.status}`),{status:r.status})}if(!r.ok)throw Object.assign(new Error(d.status||`HTTP_${r.status}`),{status:r.status,data:d});return d}
function toast(t){const e=$('toast');e.textContent=t;e.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>e.hidden=true,2600)}
function store(){localStorage.setItem('mol.session',JSON.stringify({token:S.token,user:S.user,expires:S.expires}))}
function restore(){try{const x=JSON.parse(localStorage.getItem('mol.session')||'null');if(!x?.token||!x?.user||x.expires&&new Date(x.expires)<=new Date())return false;S.token=x.token;S.user=x.user;S.expires=x.expires;return true}catch(e){return false}}
function stop(){Object.values(S.timers).forEach(clearInterval);S.timers={}}
function logout(){stop();localStorage.removeItem('mol.session');Object.assign(S,{token:null,user:null,config:null,wd:null,daily:null,monthly:null,alerts:[],team:[],leaderDirectory:[],active:null,mode:'worker'});$('appShell').hidden=true;$('loginView').hidden=false;$('appLoader').style.display='none'}
function identity(){const u=S.user||{},a=(u.name||'?')[0].toUpperCase();$('workerName').textContent=u.name||'Pracownik';$('workerRole').textContent=u.role||'';$('userAvatar').textContent=a;$('leaderName').textContent=u.name||'Lider';$('leaderRole').textContent=u.role||'';$('leaderAvatar').textContent=a;$('roleSwitch').hidden=!['LEADER','ADMIN'].includes(String(u.role).toUpperCase())}
async function login(l,p){const r=await api('auth',{method:'POST',auth:false,body:{login:l,password:p}});S.token=r.token;S.user=r.employee;S.expires=r.expires_at;store();await hydrate()}
async function hydrate(){try{$('appLoader').style.display='grid';S.config=await api('config');try{S.wd=await api('workday')}catch(e){S.wd={ok:false,status:e.message}};$('loginView').hidden=true;$('appShell').hidden=false;identity();renderGrid();renderWd();await Promise.allSettled([refreshAlerts(),daily()]);start()}catch(e){if(e.status===401)return logout();toast(e.message==='NETWORK'?'Brak połączenia z backendem.':`Błąd startu: ${e.message}`)}finally{$('appLoader').style.display='none'}}
function start(){stop();S.timers.tick=setInterval(tick,1000);S.timers.wd=setInterval(refreshWd,C.polling.workdayMs);S.timers.alerts=setInterval(refreshAlerts,C.polling.alertsMs);if(S.mode==='leader')S.timers.leader=setInterval(refreshTeam,C.polling.leaderMs)}
function renderGrid(){const rows=S.config?.processes||[];$('processGrid').innerHTML=rows.map(x=>{const m=P[x.code]||[x.name,'•','#555'];return`<button class="process-card" data-code="${esc(x.code)}"><span class="process-icon">${m[1]}</span><span><strong>${esc(x.name||m[0])}</strong><small>${x.measurable?'Proces mierzalny':'Czas raportowany'}</small></span></button>`}).join('');qa('.process-card').forEach(b=>b.onclick=()=>choose(b.dataset.code))}
function blocked(status){$('workerBlocked').hidden=false;$('workerHomeView').hidden=true;$('workerNormView').hidden=true;$('workerMessagesView').hidden=true;const h=$('workerBlocked').querySelector('h2'),p=$('workerBlocked').querySelector('p');if(status==='FINISHED'){h.textContent='Dzień w Moniti jest zakończony';p.textContent='Nie można otworzyć nowego dnia aplikacji po zakończeniu obecności w Moniti.'}else{h.textContent='Zaloguj się do Moniti';p.textContent='Nie znaleziono aktywnego START w Moniti. Po zalogowaniu sprawdź ponownie.'}}
function renderWd(){if(!S.wd?.ok)return blocked(S.wd?.status);const w=S.wd.work_day||{};$('monitiStart').textContent=time(w.moniti_start_at);$('pickerStart').textContent=time(w.moniti_start_at);$('monitiStatus').textContent=S.wd.status||'—';const finished=String(S.wd.status||'')==='FINISHED'||String(w.status||'')==='MONITI_FINISHED'||Boolean(w.moniti_end_at);if(finished){S.active=null;S.wd.active_process=null;$('processTimer').textContent='00:00:00';const warehouseTimer=$('warehouseProcessTimer');if(warehouseTimer)warehouseTimer.textContent='00:00:00';return blocked('FINISHED')}$('workerBlocked').hidden=true;workerView(S.workerView);S.active=S.wd.active_process||null;S.active?active(S.active):picker()}
function picker(){$('processPicker').hidden=false;$('activeProcessView').hidden=true;$('warehouseView').hidden=true}
function active(a){S.active=a;$('processPicker').hidden=true;$('warehouseView').hidden=true;$('activeProcessView').hidden=false;const m=P[a.process_code]||[a.process_code,'•','#2f76e8'];$('processHero').style.setProperty('--accent',m[2]);$('activeProcessName').textContent=m[0];$('activeProcessStart').textContent=time(a.start_at);tick();kpi();if(a.process_code==='MAGAZYN')warehouse()}
function warehouse(){$('processPicker').hidden=true;$('activeProcessView').hidden=true;$('warehouseView').hidden=false;$('warehouseProcessStart').textContent=time(S.active?.start_at);$('expiryAppLink').href=C.warehouse.expiryApp;$('batchReaderLink').href=C.warehouse.batchReader;tick()}
function tick(){const value=S.active?.start_at?dur((Date.now()-new Date(S.active.start_at))/1000):'00:00:00';$('processTimer').textContent=value;const warehouseTimer=$('warehouseProcessTimer');if(warehouseTimer)warehouseTimer.textContent=value}
function kpi(){const c=S.active?.process_code,r=S.daily?.report;let l='Proces niemierzalny',v='Czas';if(c==='PAKOWANIE'){l='Spakowane zamówienia';v=r?.eligible_pak??'—'}if(c==='KOMPLETACJA'){l='PIK';v=r?.eligible_pick??'—'}$('processKpiLabel').textContent=l;$('processKpiValue').textContent=v}
async function choose(code){if(!code)return;if(String(S.wd?.status||'')==='FINISHED'||String(S.wd?.work_day?.status||'')==='MONITI_FINISHED'||Boolean(S.wd?.work_day?.moniti_end_at))return blocked('FINISHED');const cur=S.active?.process_code;if(cur===code)return code==='MAGAZYN'?warehouse():active(S.active);try{const r=await api('process',{method:'POST',body:{action:cur?'change':'start',process_code:code}});S.active={session_id:r.session_id,process_code:r.process_code,start_at:r.start_at};S.wd.active_process=S.active;active(S.active);toast(`${P[code]?.[0]||code}: proces aktywny`)}catch(e){toast(({WORKDAY_NOT_OPEN:'Dzień aplikacji nie jest otwarty.',PROCESS_NOT_ALLOWED:'Nie masz dostępu do tego procesu.',ACTIVE_PROCESS_EXISTS:'Inny proces jest już aktywny.',SAME_PROCESS:'Ten proces jest już aktywny.',ES_BOUNDARY_SNAPSHOT_FAILED:'Snapshot ES nieudany. Zmiana PAK/PICK bezpiecznie zablokowana.'}[e.message]||`Operacja nieudana: ${e.message}`))}}
async function logoutProcess(){if(!S.active)return picker();try{const r=await api('process',{method:'POST',body:{action:'logout_process'}});S.active=null;if(S.wd)S.wd.active_process=null;picker();await daily();toast(r.status==='PROCESS_ALREADY_LOGGED_OUT'?'Proces był już wylogowany.':'Wylogowano z procesu. Czas pracy w Moniti nadal trwa.')}catch(e){toast(({WORKDAY_NOT_OPEN:'Dzień aplikacji nie jest otwarty.',APP_WORKDAY_ALREADY_ENDED:'Dzień pracy w aplikacji jest już zakończony.',MULTIPLE_ACTIVE_PROCESSES:'Wykryto więcej niż jeden aktywny proces.'}[e.message]||`Nie udało się wylogować z procesu: ${e.message}`))}}
async function refreshWd(){try{S.wd=await api('workday');renderWd();await daily()}catch(e){if(e.status===401)return logout();blocked(e.message)}}
async function daily(){try{S.daily=await api('reports',{method:'POST',body:{action:'daily',date:new Date().toLocaleDateString('sv-SE')}});if(S.active)kpi();if(S.workerView==='norm'&&S.norm==='daily')renderNorm()}catch(e){S.daily={ok:false}}}
async function monthly(){const d=new Date(),m=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;try{S.monthly=await api('reports',{method:'POST',body:{action:'monthly',month:m}})}catch(e){S.monthly={ok:false}}}
function workerView(v){S.workerView=v;$('workerHomeView').hidden=v!=='home';$('workerNormView').hidden=v!=='norm';$('workerMessagesView').hidden=v!=='messages';qa('.worker-nav-item').forEach(b=>b.classList.toggle('active',b.dataset.workerView===v));if(v==='norm'){if(S.norm==='monthly')monthly().then(renderNorm);else daily().then(renderNorm)}if(v==='messages')messages()}
function card(k,v,primary=false){return`<div class="metric-card ${primary?'primary-metric':''}"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`}
function renderNorm(){const root=$('normSummary'),list=$('processTimeList');if(S.norm==='monthly'){const r=S.monthly,np=r?.totals?.no_process_minutes||0,mt=r?.totals?.moniti_total_minutes||0;root.innerHTML=card('Norma miesięczna',pct(r?.monthly_norm_pct),true)+card('Eligible PAK',r?.totals?.eligible_pak||0)+card('Eligible PICK',r?.totals?.eligible_pick||0)+card('Czas międzyprocesowy',`${mins(np)} · ${share(np,mt)}`);list.innerHTML=(r?.daily_rows||[]).slice().reverse().map(d=>`<div class="time-row"><span>${esc(d.work_date)}</span><small>${mins((d.pak_minutes||0)+(d.pick_minutes||0))}</small><strong>${pct(d.daily_norm_pct)}</strong></div>`).join('')||'<div class="time-row"><span>Brak danych</span></div>';return}const r=S.daily?.report,np=r?.no_process_minutes||0,mt=r?.moniti_total_minutes||0;root.innerHTML=card('Norma dzienna',pct(r?.daily_norm_pct),true)+card('Pakowanie',`${r?.eligible_pak||0} · ${pct(r?.pak_norm_pct)}`)+card('Kompletacja / PIK',`${r?.eligible_pick||0} · ${pct(r?.pick_norm_pct)}`)+card('Czas międzyprocesowy',`${mins(np)} · ${share(np,mt)}`);list.innerHTML=Object.keys(MIN).map(c=>`<div class="time-row"><span>${esc(P[c][0])}</span><small>${mins(r?.[MIN[c]]||0)}</small><strong>${c==='PAKOWANIE'?pct(r?.pak_norm_pct):c==='KOMPLETACJA'?pct(r?.pick_norm_pct):'—'}</strong></div>`).join('')+`<div class="time-row"><span>Czas międzyprocesowy</span><small>${mins(np)}</small><strong>${share(np,mt)}</strong></div>`}
async function refreshAlerts(){if(!S.token)return;try{const r=await api('alerts',{method:'POST',body:{action:'list'}});S.alerts=r.alerts||[];badge();messages();modal()}catch(e){if(e.status===401)logout()}}
function title(t){return({INACTIVITY:'Brak aktywności',WRONG_PROCESS:'Niewłaściwy proces',NO_PROCESS:'Brak wybranego procesu',MANUAL_MESSAGE:'Wiadomość od lidera'}[t]||'Komunikat')}
function badge(){const b=$('alertCountBadge');b.textContent=S.alerts.length;b.hidden=!S.alerts.length}
function messages(){const r=$('messagesList');if(!r)return;r.innerHTML=S.alerts.map(a=>`<article class="message-card ${String(a.severity).toLowerCase()}"><h3>${esc(title(a.type))}</h3><p>${esc(a.message)}</p><footer><span>${time(a.created_at)}</span><button data-ack="${esc(a.alert_id)}">Potwierdź</button></footer></article>`).join('')||'<article class="message-card"><h3>Brak nowych komunikatów</h3><p>Nie masz teraz niepotwierdzonych alertów.</p></article>';r.querySelectorAll('[data-ack]').forEach(b=>b.onclick=()=>ack(b.dataset.ack))}
function modal(){if(S.modalAlert||!S.alerts.length)return;S.modalAlert=S.alerts[0];$('alertModalTitle').textContent=title(S.modalAlert.type);$('alertModalText').textContent=S.modalAlert.message;$('alertModal').hidden=false;navigator.vibrate?.([180,90,180])}
async function ack(id){try{await api('alerts',{method:'POST',body:{action:'ack',alert_id:id}});S.alerts=S.alerts.filter(a=>a.alert_id!==id);if(S.modalAlert?.alert_id===id){S.modalAlert=null;$('alertModal').hidden=true}badge();messages();setTimeout(modal,150)}catch(e){toast(`Nie udało się potwierdzić: ${e.message}`)}}
function confirm(title,text,fn){S.confirm=fn;$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmModal').hidden=false}
async function endDay(){try{const r=await api('process',{method:'POST',body:{action:'end'}});toast(r.status==='APP_WORKDAY_ALREADY_ENDED'?'Dzień był już zakończony.':'Zakończono pracę w aplikacji.');await refreshWd()}catch(e){toast(`Nie udało się zakończyć: ${e.message}`)}}
function mode(m){if(m==='leader'&&!['LEADER','ADMIN'].includes(String(S.user?.role).toUpperCase()))return;S.mode=m;$('workerApp').hidden=m!=='worker';$('leaderApp').hidden=m!=='leader';$('roleSwitch').textContent=m==='leader'?'Widok pracownika':'Panel lidera';if(m==='leader'){leaderView(S.leaderView);refreshTeam();refreshLeaderAlerts()}start()}
const lead=(action,p={})=>api('leader',{method:'POST',body:{action,...p}});
async function refreshTeam(){try{const r=await lead('team');S.team=r.employees||[];S.leaderDirectory=r.directory||S.team;const stale=r.source_status&&r.source_status!=='OK';$('leaderUpdated').textContent=`Ostatnia aktualizacja ${time(r.checked_at)}${stale?' · dane Moniti nieaktualne':''}`;team();selects()}catch(e){if(e.status===401)return logout();toast(`Panel lidera: ${e.message}`)}}
function chip(s,c=''){return`<span class="chip ${c}">${esc(s)}</span>`}
function team(){const x=S.team;$('kpiActiveMoniti').textContent=x.filter(e=>e.moniti_status==='ACTIVE').length;$('kpiWithProcess').textContent=x.filter(e=>e.active_process).length;$('kpiAlerts').textContent=x.reduce((a,e)=>a+(+e.active_alerts||0),0);const rows=x.map(e=>{const appChip=e.mapping_error?chip('BŁĄD MAPOWANIA','danger'):e.app_active?chip('AKTYWNA','active'):chip('BRAK APLIKACJI','warn');const processChip=e.mapping_error?chip('BŁĄD MAPOWANIA','danger'):e.active_process?chip(P[e.active_process]?.[0]||e.active_process,'active'):e.app_active?chip('BRAK PROCESU','warn'):chip('BRAK APLIKACJI');return`<tr data-id="${esc(e.employee_id)}"><td><span class="employee-cell"><span class="mini-avatar">${esc((e.name||'?')[0])}</span>${esc(e.name)}</span></td><td>${chip(e.moniti_status,e.moniti_status==='ACTIVE'?'active':e.mapping_error?'danger':'warn')}</td><td>${appChip}</td><td>${processChip}</td><td>${e.active_process?dur(e.process_elapsed_seconds):'—'}</td><td>${mins(e.no_process_minutes)}</td><td>${pct(e.pak_norm_pct)}</td><td>${pct(e.pick_norm_pct)}</td><td>${pct(e.daily_norm_pct)}</td><td>${e.active_alerts?chip(`${e.active_alerts} alert`,e.alert_severity==='CRITICAL'?'danger':'warn'):chip('OK','active')}</td></tr>`}).join('');$('teamTableBody').innerHTML=rows||'<tr><td colspan="10">Brak aktywnych pracowników w Moniti.</td></tr>';$('teamTableBody').querySelectorAll('tr[data-id]').forEach(r=>r.onclick=()=>drawer(r.dataset.id))}
function drawer(id){const e=S.team.find(x=>x.employee_id===id);if(!e)return;const appLabel=e.mapping_error?'Błąd mapowania':e.app_active?'Aktywna':'Brak aplikacji';const action=e.mapping_error?'':`<button class="btn btn-primary" data-msg="${esc(e.employee_id)}">Wyślij komunikat</button>`;$('employeeDrawerContent').innerHTML=`<p class="eyebrow">${esc(e.role)}</p><h2 class="drawer-title">${esc(e.name)}</h2><p>Moniti: ${esc(e.moniti_status)} · ${time(e.moniti_start)} – ${time(e.moniti_finish)}</p><div class="drawer-grid"><div class="drawer-stat"><small>Aplikacja</small><strong>${esc(appLabel)}</strong></div><div class="drawer-stat"><small>Czas Moniti</small><strong>${mins(e.moniti_total_minutes)}</strong></div><div class="drawer-stat"><small>Czas międzyprocesowy</small><strong>${mins(e.no_process_minutes)}</strong></div><div class="drawer-stat"><small>Proces</small><strong>${esc(P[e.active_process]?.[0]||e.active_process||(e.app_active?'BRAK PROCESU':'—'))}</strong></div><div class="drawer-stat"><small>PAK</small><strong>${pct(e.pak_norm_pct)}</strong></div><div class="drawer-stat"><small>PIK</small><strong>${pct(e.pick_norm_pct)}</strong></div><div class="drawer-stat"><small>Norma dnia</small><strong>${pct(e.daily_norm_pct)}</strong></div><div class="drawer-stat"><small>Alerty</small><strong>${e.active_alerts||0}</strong></div></div>${action}`;$('employeeDrawer').hidden=false;const button=$('employeeDrawerContent').querySelector('[data-msg]');if(button)button.onclick=ev=>{leaderView('message');$('messageEmployee').value=ev.currentTarget.dataset.msg;$('employeeDrawer').hidden=true}}
async function refreshLeaderAlerts(){try{const r=await lead('alerts');S.leaderAlerts=r.alerts||[];leaderAlerts()}catch(e){toast(`Alerty: ${e.message}`)}}
function leaderAlerts(){$('leaderAlertsList').innerHTML=S.leaderAlerts.map(a=>`<article class="leader-alert-card ${String(a.severity).toLowerCase()}"><h3>${esc(title(a.type))} · ${esc(a.employee_name||a.employee_id)}</h3><p>${esc(a.message)}</p><footer><span>${esc(a.source)} · ${time(a.created_at)}</span>${chip(a.severity)}</footer></article>`).join('')||'<article class="leader-alert-card"><h3>Brak aktywnych alertów</h3><p>System nie raportuje teraz nierozwiązanych wyjątków.</p></article>'}
function leaderView(v){S.leaderView=v;qa('.leader-view').forEach(x=>x.hidden=true);const id={monitoring:'leaderMonitoringView',alerts:'leaderAlertsView',message:'leaderMessageView',reports:'leaderReportsView'}[v];$(id).hidden=false;qa('.leader-nav-item').forEach(b=>b.classList.toggle('active',b.dataset.leaderView===v));if(v==='alerts')refreshLeaderAlerts();if(v==='monitoring')refreshTeam()}
function selects(){const messagePeople=S.team.filter(e=>!e.mapping_error&&e.employee_id);const reportPeople=S.leaderDirectory.length?S.leaderDirectory:messagePeople;const options=rows=>rows.map(e=>`<option value="${esc(e.employee_id)}">${esc(e.name)}</option>`).join('');$('messageEmployee').innerHTML=options(messagePeople);$('reportEmployee').innerHTML=options(reportPeople)}
async function sendMessage(ev){ev.preventDefault();const employee_id=$('messageEmployee').value,message=$('messageText').value.trim(),priority=document.querySelector('input[name="priority"]:checked')?.value||'NORMAL';if(!message)return;try{await lead('message_send',{employee_id,message,priority});$('messageSendStatus').textContent='Komunikat zapisany i wysłany do aplikacji pracownika.';$('messageText').value='';toast('Komunikat wysłany')}catch(e){$('messageSendStatus').textContent=`Błąd: ${e.message}`}}
const stat=(k,v)=>`<div class="report-stat"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`;
async function report(){const employee_id=$('reportEmployee').value,mode=$('reportMode').value,root=$('leaderReportContent');root.innerHTML='<div class="report-panel">Pobieranie…</div>';try{if(mode==='daily'){const x=await lead('report_daily',{employee_id,date:$('reportDate').value}),r=x.report;if(!r)return root.innerHTML='<div class="report-panel">Brak podsumowania dla dnia.</div>';root.innerHTML=`<div class="report-panel"><h3>${esc(r.employee_name||r.employee_id)} · ${esc(r.work_date)}</h3><div class="report-grid">${stat('Moniti',mins(r.moniti_total_minutes))}${stat('Czas międzyprocesowy',`${mins(r.no_process_minutes)} · ${share(r.no_process_minutes,r.moniti_total_minutes)}`)}${stat('Pakowanie',mins(r.pak_minutes))}${stat('Kompletacja',mins(r.pick_minutes))}${stat('Norma dnia',pct(r.daily_norm_pct))}${stat('Eligible PAK',r.eligible_pak)}${stat('Eligible PICK',r.eligible_pick)}${stat('Poza aplikacją',`${r.outside_app_pak||0} / ${r.outside_app_pick||0}`)}${stat('Alerty',r.alerts_count||0)}</div></div>`}else{const x=await lead('report_monthly',{employee_id,month:$('reportMonth').value});root.innerHTML=`<div class="report-panel"><h3>${esc(x.employee_id)} · ${esc(x.month)}</h3><div class="report-grid">${stat('Norma miesięczna',pct(x.monthly_norm_pct))}${stat('Dni',x.days_count||0)}${stat('Eligible PAK',x.totals?.eligible_pak||0)}${stat('Eligible PICK',x.totals?.eligible_pick||0)}${stat('PAK czas',mins(x.totals?.pak_minutes))}${stat('PICK czas',mins(x.totals?.pick_minutes))}${stat('Czas Moniti',mins(x.totals?.moniti_total_minutes))}${stat('Czas międzyprocesowy',`${mins(x.totals?.no_process_minutes)} · ${share(x.totals?.no_process_minutes,x.totals?.moniti_total_minutes)}`)}${stat('Alerty',x.totals?.alerts_count||0)}</div></div>`}}catch(e){root.innerHTML=`<div class="report-panel">Błąd: ${esc(e.message)}</div>`}}
function bind(){qa('[data-logo]').forEach(i=>i.src=window.ESTYL_LOGO);$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginButton').disabled=true;$('loginError').hidden=true;try{await login($('loginInput').value.trim(),$('passwordInput').value)}catch(x){$('loginError').hidden=false;$('loginError').textContent=({LOGIN_REQUIRED:'Podaj login.',INVALID_LOGIN_OR_PASSWORD:'Nieprawidłowy login lub hasło.',PASSWORD_NOT_SET:'Hasło dla tego pracownika nie zostało jeszcze ustawione w systemie.'}[x.message]||`Nie udało się zalogować: ${x.message}`)}finally{$('loginButton').disabled=false}};$('togglePassword').onclick=()=>$('passwordInput').type=$('passwordInput').type==='password'?'text':'password';$('logoutButton').onclick=logout;$('roleSwitch').onclick=()=>mode(S.mode==='worker'?'leader':'worker');$('workerSwitch').onclick=()=>mode('worker');qa('.worker-nav-item').forEach(b=>b.onclick=()=>workerView(b.dataset.workerView));$('backToPicker').onclick=$('changeProcessButton').onclick=$('warehouseBack').onclick=$('warehouseChangeProcessButton').onclick=picker;$('showNormButton').onclick=$('warehouseShowNormButton').onclick=()=>workerView('norm');const askProcessLogout=()=>confirm('Wylogować z procesu?','Aktywny proces zostanie zamknięty. Dzień pracy i czas w Moniti nadal będą trwały.',logoutProcess);$('logoutProcessButton').onclick=askProcessLogout;$('warehouseLogoutProcessButton').onclick=askProcessLogout;$('retryWorkday').onclick=refreshWd;qa('.segment').forEach(b=>b.onclick=async()=>{S.norm=b.dataset.norm;qa('.segment').forEach(x=>x.classList.toggle('active',x===b));S.norm==='monthly'?await monthly():await daily();renderNorm()});$('ackAlertButton').onclick=()=>S.modalAlert&&ack(S.modalAlert.alert_id);$('endDayButton').onclick=()=>confirm('Zakończyć pracę w aplikacji?','Aktywny proces zostanie zamknięty. Moniti pozostaje źródłem obecności.',endDay);$('confirmCancel').onclick=()=>{$('confirmModal').hidden=true;S.confirm=null};$('confirmAccept').onclick=async()=>{const f=S.confirm;$('confirmModal').hidden=true;S.confirm=null;if(f)await f()};qa('.leader-nav-item').forEach(b=>b.onclick=()=>leaderView(b.dataset.leaderView));$('refreshLeader').onclick=refreshTeam;$('refreshLeaderAlerts').onclick=refreshLeaderAlerts;$('closeEmployeeDrawer').onclick=()=>$('employeeDrawer').hidden=true;$('leaderMessageForm').onsubmit=sendMessage;$('loadLeaderReport').onclick=report;$('reportMode').onchange=()=>{const d=$('reportMode').value==='daily';$('reportDateWrap').hidden=!d;$('reportMonthWrap').hidden=d};window.addEventListener('online',()=>online(true));window.addEventListener('offline',()=>online(false))}
async function boot(){bind();$('appVersion').textContent=`v${C.version}`;$('expiryAppLink').href=C.warehouse.expiryApp;$('batchReaderLink').href=C.warehouse.batchReader;const d=new Date();$('reportDate').value=d.toLocaleDateString('sv-SE');$('reportMonth').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});restore()?await hydrate():logout()}
boot();})();
