import {graph,ex,manifest} from './graph.mjs';
export function summaryRecalculator(){const g=graph('SUMMARY RECALCULATOR',120);g.input();
 g.code('Context',String.raw`const i=$input.first().json;if(!/^MOL[0-9]+$/.test(i.employee_id||'')||!/^\d{4}-\d{2}-\d{2}$/.test(i.work_date||'')||!DateTime.fromISO(i.work_date).isValid||i.work_date>DateTime.now().setZone('Europe/Warsaw').toISODate())throw Error('SUMMARY_SCOPE_INVALID');return [{json:{employee_id:i.employee_id,work_date:i.work_date,aggregate_id:i.employee_id+':'+i.work_date,month:i.work_date.slice(0,7),summary_id:i.employee_id+':'+i.work_date.slice(0,7)}}];`);
 g.table('Acquire Writer','LOCKS','update',[['lock_key','command-writer'],['owner','']],{owner:ex('String($execution.id)'),lease_until:ex('$now.plus({seconds:120}).toISO()')});
 g.test('Owns Writer','$json.owner === String($execution.id)');g.code('Busy',"return [{json:{ok:false,error_code:'COMMAND_BUSY'}}];");
 const aggregate=ex("$('Context').first().json.aggregate_id");
 g.table('Read Attendance','ATTENDANCE','get',[['attendance_id',aggregate]]);
 g.table('Read Processes','PROCESS_SESSIONS','get',[['attendance_id',aggregate]],{},true);
 g.table('Read Deltas','PRODUCTION_DELTAS','get',[['attendance_id',aggregate]],{},true);
 // A boundary poll also observes other employees. Load its source command by ID,
 // not only by the current employee/day, before qualifying any boundary batch.
 g.code('Build Boundary Requests',"const ids=[...new Set($('Read Deltas').all().map(x=>x.json.delta_id).filter(x=>typeof x==='string'&&x.startsWith('ESB-')).map(x=>x.slice(4,40)))];return (ids.length?ids:['__NONE__']).map(source_request_id=>({json:{source_request_id}}));");
 g.table('Read Boundary Commands','COMMANDS','get',[['request_id',ex('$json.source_request_id')]]);g.nodes.at(-1).executeOnce=false;
 g.table('Read Commands','COMMANDS','get',[['aggregate_id',aggregate]],{},true);
 g.table('Read Pending Batch','ES_BATCHES','get',[['status','PREPARED']]);
 g.table('Read Checkpoint','ES_POLL_STATE','get',[['checkpoint_id',aggregate]]);
 g.table('Read Current Checkpoint','ES_POLL_STATE','get',[['checkpoint_id',ex("$('Context').first().json.employee_id+':'+($('Read Attendance').first().json.stop_at?DateTime.fromISO($('Read Attendance').first().json.stop_at).setZone('Europe/Warsaw').toISODate():DateTime.now().setZone('Europe/Warsaw').toISODate())")]]);
 g.table('Read Month','NORM_SNAPSHOTS','get',[['summary_id',ex("$('Context').first().json.summary_id")]]);
 g.table('Read Employees','EMPLOYEES','get',[['active',true]],{},true);g.config();g.table('Read Jobs','OUTBOX','get',[['aggregate_id',aggregate]],{},true);
 g.code('Build Input',"const c=$('Context').first().json,a=$('Read Attendance').all().map(x=>x.json).filter(x=>x.attendance_id),old=$('Read Month').all().map(x=>x.json).filter(x=>x.summary_id),commands=$('Read Commands').all().map(x=>x.json).filter(x=>x.request_id);if(a.length>1||old.length>1)throw Error('SUMMARY_DUPLICATE');if(commands.some(x=>!['COMMITTED','FAILED'].includes(x.status))||$('Read Pending Batch').all().map(x=>x.json).some(x=>x.batch_id))return [{json:{ok:false,blocked:true,error_code:'SOURCE_RECOVERY_REQUIRED'}}];const cfg={};for(const x of $('Read Config').all().map(x=>x.json))if(x.key&&!x.key.startsWith('ALLOWED_PROCESSES_')){if(Object.hasOwn(cfg,x.key))throw Error('CONFIG_DUPLICATE');cfg[x.key]=JSON.parse(x.value_json);}const effective=a[0]?.state==='OPEN'?DateTime.now().setZone('Europe/Warsaw').toISODate():a[0]?.stop_at?DateTime.fromISO(a[0].stop_at).setZone('Europe/Warsaw').toISODate():c.work_date;const current=c.work_date!==effective;const cps=(current?$('Read Current Checkpoint').all().map(x=>x.json):$('Read Checkpoint').all().map(x=>x.json)).filter(x=>x.checkpoint_id);if(cps.length>1)throw Error('ES_CHECKPOINT_DUPLICATE');const boundaries=$('Read Boundary Commands').all().map(x=>x.json).filter(x=>x.request_id);if(new Set(boundaries.map(x=>x.request_id)).size!==boundaries.length)throw Error('BOUNDARY_COMMAND_DUPLICATE');const sources=[...new Map([...commands,...boundaries].map(x=>[x.request_id,{request_id:x.request_id,status:x.status}])).values()];return [{json:{kind:'SUMMARY',previous_month:old[0]||null,employees:$('Read Employees').all().map(x=>x.json).filter(x=>x.employee_id).map(x=>({employee_id:x.employee_id,active:x.active,es_worker_id:x.es_worker_id})),input:{...c,attendance:a[0]||null,processes:$('Read Processes').all().map(x=>x.json).filter(x=>x.process_session_id),deltas:$('Read Deltas').all().map(x=>x.json).filter(x=>x.delta_id),commands:sources,checkpoint:cps[0]||null,now:new Date().toISOString(),stale_seconds:Number(cfg.ES_STALE_SECONDS)||180}}}];");
 g.test('Source Ready','$json.blocked !== true');g.execute('Calculate',manifest.workflows.metrics_rules);g.test('Calculated','$json.ok === true');
 g.code('Failure Tasks',"const c=$('Context').first().json,error=$('Calculate').first().json.error_code;const jobs=$('Read Jobs').all().map(x=>x.json).filter(j=>j.outbox_id&&['ATTENDANCE_DERIVED','ES_DERIVED'].includes(j.type)&&['PENDING','RETRY_PENDING'].includes(j.status)&&Date.parse(j.next_attempt_at)<=Date.now()).slice(0,8);return jobs.length?jobs.map(j=>({json:{lock_owner:String($execution.id),job_id:j.outbox_id,aggregate_id:c.aggregate_id,summary_id:c.summary_id,result:'failure',error_code:error}})):[{json:{noop:true}}];");
 for(const [name,table,prop,keys] of [
 ['Daily','DAILY_SUMMARY','daily',['summary_id','employee_id','work_date','presence_seconds','process_seconds','between_process_seconds','pak_seconds','pick_seconds','eligible_pak','eligible_pick','pak_percent','pick_percent','combined_percent','freshness','calculated_at','version']],
 ['Monthly','MONTHLY_SUMMARY','monthly',['summary_id','employee_id','month','pak_seconds','pick_seconds','eligible_pak','eligible_pick','combined_percent','freshness','calculated_at','version']]]){
  g.code(name+' Item',`const d=$('Calculate').first().json.${prop},p=$('Calculate').first().json.publication,keys=${JSON.stringify(keys)};return [{json:{lock_owner:String($execution.id),table:'${table}',mode:'replace',row:Object.fromEntries(keys.map(k=>[k,k==='version'?p.version:d[k]??null]))}}];`);g.writer('Save '+name);
 }
 g.code('Publication',"const x=$('Calculate').first().json.publication;return [{json:{lock_owner:String($execution.id),table:'NORM_SNAPSHOTS',mode:'replace',row:x}}];");g.writer('Save Publication');
 g.code('Mirror Task',"const p=$('Calculate').first().json.publication,request='NORM:'+p.summary_id+':'+p.version;return [{json:{lock_owner:String($execution.id),table:'OUTBOX',mode:'insert_only',row:{outbox_id:request+':drive',request_id:request,aggregate_id:p.summary_id,type:'NORM_DRIVE',payload_json:JSON.stringify({summary_id:p.summary_id,version:p.version}),status:'PENDING',attempts:0,next_attempt_at:p.calculated_at,lease_owner:'',lease_until:'1970-01-01T00:00:00.000Z',last_error:''}}}];");g.writer('Save Mirror Task');
 g.code('Success Tasks',"const c=$('Context').first().json,p=$('Calculate').first().json.publication;const jobs=$('Read Jobs').all().map(x=>x.json).filter(j=>j.outbox_id&&['ATTENDANCE_DERIVED','ES_DERIVED'].includes(j.type)&&['PENDING','RETRY_PENDING'].includes(j.status)&&Date.parse(j.next_attempt_at)<=Date.now()).slice(0,8);return jobs.length?jobs.map(j=>({json:{lock_owner:String($execution.id),job_id:j.outbox_id,aggregate_id:c.aggregate_id,summary_id:c.summary_id,summary_version:p.version,result:'success'}})):[{json:{noop:true}}];");
 g.test('Has Tasks','$json.noop !== true');g.execute('Complete Tasks',manifest.workflows.metrics_task_ack,'each');
 g.code('Result',"const d=$('Calculate').first().json;return [{json:d.ok===true?{ok:true,summary_id:d.publication.summary_id,work_date:$('Context').first().json.work_date,version:d.publication.version,freshness:d.daily.freshness,combined_percent:d.daily.combined_percent}:{ok:false,error_code:d.error_code}}];");
 g.code('Finish','return $input.all();');g.table('Release Writer','LOCKS','update',[['lock_key','command-writer'],['owner',ex('String($execution.id)')]],{owner:'',lease_until:'1970-01-01T00:00:00.000Z'});g.code('Return',"return [{json:$('Finish').first().json}];");
 g.chain('Input','Context','Acquire Writer','Owns Writer');g.link('Owns Writer','Read Attendance');g.link('Owns Writer','Busy',1);
 g.chain('Read Attendance','Read Processes','Read Deltas','Build Boundary Requests','Read Boundary Commands','Read Commands','Read Pending Batch','Read Checkpoint','Read Current Checkpoint','Read Month','Read Employees','Read Config','Read Jobs','Build Input','Source Ready');
 g.link('Source Ready','Calculate');g.link('Source Ready','Finish',1);g.chain('Calculate','Calculated');g.link('Calculated','Daily Item');g.link('Calculated','Failure Tasks',1);g.link('Failure Tasks','Has Tasks');
 g.chain('Daily Item','Save Daily','Monthly Item','Save Monthly','Publication','Save Publication','Mirror Task','Save Mirror Task','Success Tasks','Has Tasks');g.link('Has Tasks','Complete Tasks');g.link('Has Tasks','Result',1);g.chain('Complete Tasks','Result','Finish','Release Writer','Return');return g;
}
if(process.argv[1]?.endsWith('/metrics/build-summary.mjs'))console.log(JSON.stringify(summaryRecalculator(),null,2));
