import {graph,ex,manifest} from './graph.mjs';
export function recordWriter(){
 const g=graph('METRICS RECORD WRITER',30);g.input();
 const keys={ES_POLL_STATE:'checkpoint_id',ES_BATCHES:'batch_id',PRODUCTION_DELTAS:'delta_id',NORM_SNAPSHOTS:'summary_id',STATUS_SNAPSHOTS:'view_id',DAILY_SUMMARY:'summary_id',MONTHLY_SUMMARY:'summary_id',OUTBOX:'outbox_id',REPORT_INDEX:'report_key'};
 const tables=Object.fromEntries(Object.entries(keys).map(([k,v])=>[k,[manifest.tables['MOL_V2_'+k],v]]));
 g.code('Validate Record',`const i=$input.first().json;const tables=${JSON.stringify(tables)};`+String.raw`if(typeof i.lock_owner!=='string'||!/^\d+$/.test(i.lock_owner))throw Error('METRICS_LOCK_REQUIRED');const lock_key=i.table==='REPORT_INDEX'?'norm-drive-writer':'command-writer';if(i.noop===true)return [{json:{noop:true,lock_owner:i.lock_owner,lock_key}}];const t=tables[i.table];if(!t||!i.row||Array.isArray(i.row)||typeof i.row[t[1]]!=='string'||!i.row[t[1]]||Object.hasOwn(i.row,'id')||!['immutable','insert_only','replace'].includes(i.mode))throw Error('METRICS_RECORD_INVALID');if(i.table==='PRODUCTION_DELTAS'&&i.mode!=='immutable')throw Error('DELTA_IMMUTABLE');if(i.table==='OUTBOX'&&i.mode!=='insert_only')throw Error('OUTBOX_INSERT_ONLY');return [{json:{...i,table_id:t[0],key:t[1],lock_key}}];`);
 g.table('Read Lock','LOCKS','get',[['lock_key',ex("$('Validate Record').first().json.lock_key")],['owner',ex("$('Validate Record').first().json.lock_owner")]]);
 g.code('Check Lock',"const i=$('Validate Record').first().json,rows=$input.all().map(x=>x.json).filter(r=>r.lock_key);if(rows.length!==1||rows[0].owner!==i.lock_owner)throw Error('METRICS_LOCK_LOST');return [{json:i.noop?{ok:true,noop:true,skipped:true}:{ready:true}}];");
 g.test('Ready','$json.ready === true');
 const table=ex("$('Validate Record').first().json.table_id"),key=ex("$('Validate Record').first().json.key"),value=ex("$('Validate Record').first().json.row[$('Validate Record').first().json.key]");
 g.dynamic('Read Existing',table,key,value);
 g.code('Decide Write',"const i=$('Validate Record').first().json,rs=$input.all().map(x=>x.json).filter(r=>r[i.key]!==undefined);if(rs.length>1)throw Error('METRICS_DUPLICATE_RECORD');const old=rs[0];const same=old&&Object.entries(i.row).every(([k,v])=>k.endsWith('_at')||k==='source_time'?(v?Date.parse(v):null)===(old[k]?Date.parse(old[k]):null):v===old[k]);if(same)return [{json:{ok:true,skipped:true,verified:true,table:i.table,key:i.row[i.key]}}];if(old&&i.mode==='immutable')throw Error('IMMUTABLE_RECORD_CONFLICT');if(old&&i.mode==='insert_only'){const keys=i.table==='OUTBOX'?['request_id','aggregate_id','type','payload_json']:[i.key];if(keys.some(k=>old[k]!==i.row[k]))throw Error('INSERT_ID_CONFLICT');return [{json:{ok:true,skipped:true,verified:true,table:i.table,key:i.row[i.key]}}];}if(i.expected_version!==undefined&&(old?.version||0)!==i.expected_version)throw Error('METRICS_VERSION_CONFLICT');if(i.expected_status!==undefined&&(old?.status||null)!==i.expected_status)throw Error('METRICS_STATUS_CONFLICT');return [{json:{write:true}}];");
 g.test('Needs Write','$json.write === true');g.code('Row Only',"return [{json:$('Validate Record').first().json.row}];");
 g.dynamic('Write Row',table,key,value,'upsert');g.dynamic('Read Back',table,key,value);
 g.code('Verify',"const i=$('Validate Record').first().json,rs=$input.all().map(x=>x.json).filter(r=>r[i.key]!==undefined);if(rs.length!==1||Object.entries(i.row).some(([k,v])=>k.endsWith('_at')||k==='source_time'?(v?Date.parse(v):null)!==(rs[0][k]?Date.parse(rs[0][k]):null):v!==rs[0][k]))throw Error('METRICS_WRITE_NOT_CONFIRMED');return [{json:{ok:true,verified:true,table:i.table,key:i.row[i.key]}}];");
 g.code('Return','return $input.all();');
 g.chain('Input','Validate Record','Read Lock','Check Lock','Ready');g.link('Ready','Read Existing');g.link('Ready','Return',1);g.chain('Read Existing','Decide Write','Needs Write');g.link('Needs Write','Row Only');g.link('Needs Write','Return',1);g.chain('Row Only','Write Row','Read Back','Verify','Return');return g;
}
if(process.argv[1]?.endsWith('/metrics/build-writer.mjs'))console.log(JSON.stringify(recordWriter(),null,2));
