import {graph,ex,manifest} from './graph.mjs';
export function taskAck(){const g=graph('METRICS TASK ACK',30);g.input();
 g.code('Context',String.raw`const i=$input.first().json;if(!/^\d+$/.test(i.lock_owner||'')||typeof i.job_id!=='string'||!['success','failure'].includes(i.result))throw Error('METRICS_ACK_INVALID');return [{json:i}];`);
 g.table('Read Lock','LOCKS','get',[['lock_key','command-writer'],['owner',ex("$('Context').first().json.lock_owner")]]);
 g.code('Check Lock',"const rows=$input.all().map(x=>x.json).filter(x=>x.lock_key);if(rows.length!==1)throw Error('METRICS_LOCK_LOST');return [{json:{ok:true}}];");
 g.table('Read Job','OUTBOX','get',[['outbox_id',ex("$('Context').first().json.job_id")]]);
 g.code('Job',"const xs=$input.all().map(x=>x.json).filter(x=>x.outbox_id),j=xs[0];if(xs.length!==1||!['ATTENDANCE_DERIVED','ES_DERIVED'].includes(j.type))return [{json:{skip:true}}];if(['DONE','DEAD_LETTER'].includes(j.status)||Date.parse(j.next_attempt_at)>Date.now())return [{json:{skip:true}}];const c=$('Context').first().json;if(c.aggregate_id!==j.aggregate_id)throw Error('ACK_SCOPE_MISMATCH');return [{json:{...j,source_table:j.type==='ATTENDANCE_DERIVED'?'Oz0NtvJ9SRaVFMc8':'fj3jJKgoY06BVtu5',source_key:j.type==='ATTENDANCE_DERIVED'?'request_id':'batch_id'}}];");
 g.test('Due','$json.skip !== true');g.dynamic('Read Source',ex("$('Job').first().json.source_table"),ex("$('Job').first().json.source_key"),ex("$('Job').first().json.request_id"));
 g.table('Read Publication','NORM_SNAPSHOTS','get',[['summary_id',ex("$('Context').first().json.summary_id")]]);
 g.code('Decision',"const c=$('Context').first().json,j=$('Job').first().json,sources=$('Read Source').all().map(x=>x.json).filter(x=>x[j.source_key]),pubs=$input.all().map(x=>x.json).filter(x=>x.summary_id);if(sources.length!==1||sources[0].status!=='COMMITTED')return [{json:{skip:true,reason:'SOURCE_NOT_COMMITTED'}}];let p;if(c.result==='success'){if(pubs.length!==1||pubs[0].version<c.summary_version)throw Error('ACK_PUBLICATION_NOT_CONFIRMED');p=JSON.parse(pubs[0].payload_json);if(!p.days.some(d=>d.summary_id===j.aggregate_id))throw Error('ACK_DAY_MISSING');}const attempts=(j.attempts||0)+1;const success=c.result==='success',status=success?'DONE':attempts>=8?'DEAD_LETTER':'RETRY_PENDING';return [{json:{success,status,attempts,next_attempt_at:success?j.next_attempt_at:new Date(Date.now()+Math.min(1800000,30000*2**Math.min(attempts,6))).toISOString(),completed_at:success?new Date().toISOString():null,last_error:success?'':String(c.error_code||'METRICS_RECALC_FAILED').slice(0,100)}}];");
 g.test('Source Ready','$json.skip !== true');g.test('Success','$json.success === true');
 g.code('Alert Handoff',"const j=$('Job').first().json;return [{json:{lock_owner:$('Context').first().json.lock_owner,table:'OUTBOX',mode:'insert_only',row:{outbox_id:j.outbox_id+':alerts',request_id:j.request_id,aggregate_id:j.aggregate_id,type:'ALERT_DERIVED',payload_json:j.payload_json,status:'PENDING',attempts:0,next_attempt_at:new Date().toISOString(),lease_owner:'',lease_until:'1970-01-01T00:00:00.000Z',last_error:''}}}];");
 g.writer('Save Handoff');
 const fields=Object.fromEntries(['status','attempts','next_attempt_at','completed_at','last_error'].map(k=>[k,ex("$('Decision').first().json."+k)]));
 g.table('Update Job','OUTBOX','update',[['outbox_id',ex("$('Job').first().json.outbox_id")],['status',ex("$('Job').first().json.status")],['attempts',ex("$('Job').first().json.attempts")]],{...fields,lease_owner:'',lease_until:'1970-01-01T00:00:00.000Z'});
 g.code('Verify Ack',"const a=$input.first().json,d=$('Decision').first().json;if(a.outbox_id!==$('Job').first().json.outbox_id||a.status!==d.status||a.attempts!==d.attempts)throw Error('METRICS_ACK_NOT_CONFIRMED');return [{json:{ok:true,outbox_id:a.outbox_id,status:a.status}}];");g.code('Return','return $input.all();');
 g.chain('Input','Context','Read Lock','Check Lock','Read Job','Job','Due');g.link('Due','Read Source');g.link('Due','Return',1);g.chain('Read Source','Read Publication','Decision','Source Ready');g.link('Source Ready','Success');g.link('Source Ready','Return',1);g.link('Success','Alert Handoff');g.link('Success','Update Job',1);g.chain('Alert Handoff','Save Handoff','Update Job','Verify Ack','Return');return g;}
if(process.argv[1]?.endsWith('/metrics/build-ack.mjs'))console.log(JSON.stringify(taskAck(),null,2));
