(() => {
  'use strict';

  const BASE = 'https://n8n.estyl.team/webhook/';
  const SESSION_KEY = 'mol.v3.session';
  const BUILD = '20260911.9';
  const ROUTE_OVERRIDES = Object.freeze({
    'mol-app-health': 'mol-app-v3-health',
    'mol-app-v2-auth-login': 'mol-app-v3-auth-login',
    'mol-app-v2-auth-session': 'mol-app-v3-auth-session',
    'mol-app-v2-auth-logout': 'mol-app-v3-auth-logout',
  });
  const FEATURES = Object.freeze({ health: true, auth: true });
  const state = { token: '' };
  try { state.token = sessionStorage.getItem(SESSION_KEY) || ''; } catch {}
  class MOLApiError extends Error { constructor(message,{status=0,code='',retryable=false,details=null}={}){super(message);this.name='MOLApiError';this.status=status;this.code=code;this.retryable=retryable;this.details=details;} }
  const requestId=()=>globalThis.crypto?.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16);});
  const todayISO=()=>{const p=new Intl.DateTimeFormat('en',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const m=Object.fromEntries(p.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`;};
  const setToken=t=>{state.token=String(t||'');try{state.token?sessionStorage.setItem(SESSION_KEY,state.token):sessionStorage.removeItem(SESSION_KEY);}catch{}};
  const clearToken=()=>setToken(''); const getToken=()=>state.token;
  const endpoint=path=>{const n=String(path||'').replace(/^\/+/, '');if(ROUTE_OVERRIDES[n])return ROUTE_OVERRIDES[n];if(n==='mol-app-v2-message-send')return'mol-app-v2-leader-message';return n;};
  const readQuery=(path,query)=>{const n=endpoint(path),q=query&&typeof query==='object'&&!Array.isArray(query)?{...query}:{},d=todayISO();if(n==='mol-app-v2-worker-status'&&!q.work_date)q.work_date=d;if(n==='mol-app-v2-leader-team'&&!q.work_date)q.work_date=d;if(n==='mol-app-v2-norms-daily'&&!q.date&&!q.work_date)q.date=d;if(n==='mol-app-v2-norms-monthly'&&!q.month)q.month=d.slice(0,7);return q;};
  const unwrapEnvelope=value=>{let e=value;if(typeof e==='string'){try{e=JSON.parse(e);}catch{}}if(Array.isArray(e)&&e.length===1&&e[0]&&typeof e[0]==='object')e=e[0];if(e&&typeof e==='object'&&e.ok===undefined&&e.body&&typeof e.body==='object')e=e.body;return e;};
  async function request(path,{method='GET',query=null,body=null,auth=true,binary=false,timeoutMs=45000,headers:extraHeaders=null}={}){const n=endpoint(path),url=new URL(BASE+n),effectiveQuery=String(method).toUpperCase()==='GET'?readQuery(n,query):(query||{});for(const[k,v]of Object.entries(effectiveQuery)){if(v===undefined||v===null||v==='')continue;url.searchParams.set(k,Array.isArray(v)?v.join(','):String(v));}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs),headers={Accept:'application/json',...(extraHeaders||{})};if(auth){if(!state.token)throw new MOLApiError('Brak aktywnej sesji.',{status:401,code:'UNAUTHENTICATED'});headers.Authorization=`Bearer ${state.token}`;}if(body!==null)headers['Content-Type']='application/json';try{const response=await fetch(url,{method,cache:'no-store',credentials:'omit',headers,body:body!==null?JSON.stringify(body):undefined,signal:controller.signal});if(binary){if(!response.ok)throw new MOLApiError(`HTTP ${response.status}`,{status:response.status});return{blob:await response.blob(),disposition:response.headers.get('content-disposition')||'',contentType:response.headers.get('content-type')||''};}const raw=(await response.text()).replace(/^\uFEFF/,'');if(!raw.trim())throw new MOLApiError(`Backend ${n} zwrócił pustą odpowiedź (HTTP ${response.status}).`,{status:response.status,code:'EMPTY_RESPONSE',retryable:response.status>=500});let parsed;try{parsed=JSON.parse(raw);}catch{throw new MOLApiError(`Backend ${n} zwrócił niepoprawny JSON (HTTP ${response.status}).`,{status:response.status,code:'INVALID_JSON',retryable:response.status>=500});}const envelope=unwrapEnvelope(parsed);if(!response.ok||envelope?.ok!==true)throw new MOLApiError(envelope?.error?.message||'Operacja nie została potwierdzona.',{status:response.status,code:envelope?.error?.code||'',retryable:envelope?.error?.retryable===true,details:envelope?.error?.details||null});return envelope.data;}catch(error){if(error?.name==='AbortError'||error instanceof TypeError)throw new MOLApiError('Brak potwierdzenia z serwera. Sprawdź połączenie i spróbuj ponownie.',{retryable:true});throw error;}finally{clearTimeout(timer);}}
  async function login(loginName,password,{surface='mobile'}={}){const safeSurface=surface==='web'?'web':'mobile',body={request_id:requestId(),login:String(loginName||'').trim(),password:String(password||''),surface:safeSurface};try{const data=await request('mol-app-v2-auth-login',{method:'POST',body,auth:false,timeoutMs:120000});if(!/^[0-9a-f]{64}$/.test(String(data?.session_token||''))||!data?.user?.employee_id)throw new MOLApiError('Backend zwrócił nieprawidłową sesję.');setToken(data.session_token);return data;}finally{body.password='';}}
  const health=()=>request('mol-app-health',{auth:false,timeoutMs:15000});
  const session=({surface='mobile'}={})=>request('mol-app-v2-auth-session',{timeoutMs:30000,headers:{'X-MOL-Surface':surface==='web'?'web':'mobile'}});
  async function logout({clearOnFailure=false}={}){if(!state.token){clearToken();return{alreadyInactive:true};}const body={request_id:requestId()};try{const data=await request('mol-app-v2-auth-logout',{method:'POST',body,timeoutMs:30000});clearToken();return data;}catch(error){if(error.status===401||clearOnFailure)clearToken();throw error;}}
  async function requireSession({surface='mobile'}={}){if(!state.token)return null;try{const data=await session({surface}),role=String(data?.user?.role||'').toUpperCase();if(!data?.user?.employee_id||!['WORKER','LEADER','ADMIN'].includes(role))throw new MOLApiError('Nieprawidłowy zakres sesji.',{status:401,code:'UNAUTHENTICATED'});if(surface==='web'&&role==='WORKER')throw new MOLApiError('Panel WWW jest dostępny tylko dla LEADER/ADMIN.',{status:403,code:'FORBIDDEN'});return data;}catch(error){if(error.status===401||error.status===403)clearToken();throw error;}}
  const read=(path,query=null)=>request(path,{query}); const write=(path,body)=>request(endpoint(path),{method:'POST',body});
  async function download(path,query,fallbackName){const result=await request(path,{query,binary:true}),match=/filename="?([^";]+)"?/i.exec(result.disposition),filename=match?.[1]||fallbackName||'mol-v2-export.bin',url=URL.createObjectURL(result.blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200);return filename;}
  function redirectLogin(reason=''){const params=new URLSearchParams();if(reason)params.set('reason',reason);params.set('v',BUILD);location.replace(`./login.html?${params}`);}
  function canonicalizeRole(role){const expected=String(role||'').toUpperCase(),params=new URLSearchParams(location.search),current=String(params.get('role')||'').toUpperCase();params.set('v',BUILD);if(current===expected&&new URLSearchParams(location.search).get('v')===BUILD)return false;params.set('role',expected);location.replace(`${location.pathname}?${params}${location.hash||''}`);return true;}
  function reveal(){document.documentElement.classList.remove('mol-live-pending');document.getElementById('molLivePendingStyle')?.remove();}
  window.MOLApi=Object.freeze({BASE,BUILD,SESSION_KEY,ROUTE_OVERRIDES,FEATURES,MOLApiError,requestId,todayISO,getToken,setToken,clearToken,request,read,write,login,health,logout,session,requireSession,download,redirectLogin,canonicalizeRole,reveal});
})();
