(() => {
  'use strict';
  const api=window.MOLApi;if(!api)return;
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  const waitFor=async(sel,t=6000)=>{const s=Date.now();while(Date.now()-s<t){const n=document.querySelector(sel);if(n)return n;await sleep(30)}return null};
  const duration=sec=>{const s=Math.max(0,Math.floor(Number(sec)||0));return `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}`};
  const clock=v=>v?new Date(v).toLocaleTimeString('pl-PL',{timeZone:'Europe/Warsaw',hour:'2-digit',minute:'2-digit'}):'—';
  const percent=v=>Number.isFinite(Number(v))?`${Math.round(Number(v)*10)/10}%`:'—';
  const number=(v,d=0)=>Number.isFinite(Number(v))?Number(v).toLocaleString('pl-PL',{maximumFractionDigits:d}):'0';
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const monthStart=()=>`${today().slice(0,7)}-01`;
  const pname=code=>window.MOLProcesses?.byCode(code)?.name||code||'Brak procesu';
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let session=null,role='',workerStatus=null,teamData=null,initialised=false;
  function statusBar(){let b=document.querySelector('[data-live-integration-status]');if(b)return b;b=document.createElement('div');b.dataset.liveIntegrationStatus='true';b.style.cssText='position:sticky;top:0;z-index:80;margin:0 auto 10px;max-width:560px;padding:9px 12px;border:1px solid rgba(18,200,255,.28);border-radius:10px;background:rgba(3,20,31,.96);color:#bfefff;font:600 12px/1.35 system-ui';document.querySelector('.worker-shell')?.prepend(b);return b}
  function setStatus(text,state='info'){const b=statusBar();b.textContent=text;b.style.borderColor=state==='error'?'rgba(255,82,97,.65)':state==='ok'?'rgba(25,231,160,.55)':'rgba(18,200,255,.28)';b.style.color=state==='error'?'#ff9aa4':state==='ok'?'#86f4c9':'#bfefff'}
  function cleanBrand(){document.querySelectorAll('.estyl-brand-logo').forEach(n=>n.remove());document.querySelectorAll('.brand-mark').forEach(n=>{n.replaceChildren();n.textContent='◆'})}
  function identity(){const u=session?.user||{},name=u.display_name||u.employee_id||'Użytkownik',h=document.querySelector('.worker-identity h1'),a=document.querySelector('.worker-identity .avatar'),chip=document.getElementById('mobileRoleChip'),label=document.getElementById('mobilePanelLabel');if(h)h.textContent=name;if(a)a.textContent=name.trim().charAt(0).toUpperCase()||'M';if(chip)chip.textContent=role;if(label)label.textContent=role==='WORKER'?'Panel pracownika':'Panel mobilny · tryb roli'}
  function setNorm(drawer,norm){if(!drawer)return;const summary=drawer.querySelector('summary b');if(summary)summary.textContent=percent(norm?.combined_percent);const blocks=drawer.querySelectorAll('.performance-breakdown'),write=(b,v)=>{const ns=b?.querySelectorAll('.performance-metrics span b')||[];v.forEach((x,i)=>{if(ns[i])ns[i].textContent=x})};write(blocks[0],[number(norm?.total_pak),number(norm?.eligible_pak),number(norm?.outside_pak),duration(norm?.pak_seconds),percent(norm?.pak_percent)]);write(blocks[1],[number(norm?.total_pick),number(norm?.eligible_pick),number(norm?.outside_pick),duration(norm?.pick_seconds),percent(norm?.pick_percent)]);write(blocks[2],[number(norm?.total_combined_units,1),number(norm?.eligible_combined_units,1),number(norm?.outside_combined_units,1),duration(norm?.combined_seconds),percent(norm?.combined_percent)])}
  async function renderProcess(data){const p=await waitFor('[data-panel="process"]');if(!p)return;const active=data?.active_process||null,name=p.querySelector('[data-current-process-name]'),code=p.querySelector('[data-current-process-code]'),state=p.querySelector('[data-process-active-state]'),wh=p.querySelector('[data-warehouse-tools]');if(name)name.textContent=active?pname(active.process_code):'Brak aktywnego procesu';if(code)code.textContent=active?.process_code||'—';if(state)state.textContent=active?'AKTYWNY':'BRAK PROCESU';if(wh)wh.hidden=active?.process_code!=='MAGAZYN'}
  async function renderProfile(data){const p=await waitFor('[data-panel="profile"] .profile-grid');if(!p)return;const cards=p.querySelectorAll('.profile-card');if(cards[1]){const sessions=Array.isArray(data?.process_sessions)?data.process_sessions:[];cards[1].innerHTML=`<h3>Dzisiejsza historia</h3><div class="profile-row"><span>START pracy</span><strong>${clock(data?.attendance?.start_at)}</strong></div>${sessions.map(x=>`<div class="profile-row"><span>${esc(pname(x.process_code))}</span><strong>${clock(x.start_at)}–${x.stop_at?clock(x.stop_at):'teraz'}</strong></div>`).join('')||'<div class="profile-row"><span>Procesy</span><strong>brak</strong></div>'}`;}const logout=[...p.querySelectorAll('button')].find(b=>/Wyloguj/i.test(b.textContent));if(logout&&!logout.dataset.liveBound){logout.dataset.liveBound='1';logout.disabled=false;logout.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();try{await api.logout()}catch(err){if(err.status!==401)return setStatus(err.message,'error')}api.redirectLogin('session')},true)}}
  function renderWorker(data){workerStatus=data;const att=data?.attendance||null,active=data?.active_process||null,title=document.querySelector('.work-status h2'),chip=document.querySelector('.work-status .status-head .mol-chip');if(title)title.textContent=att?.state==='OPEN'?'W PRACY':att?.state==='CLOSED'?'DZIEŃ ZAKOŃCZONY':'NIE ROZPOCZĘTO';if(chip)chip.textContent=active?.process_code||'BRAK PROCESU';const stats=document.querySelectorAll('.work-status .status-stats strong');if(stats[0])stats[0].textContent=clock(att?.start_at);if(stats[1])stats[1].textContent=duration(data?.presence_seconds);if(stats[2])stats[2].textContent=active?.start_at?duration((Date.now()-Date.parse(active.start_at))/1000):'00:00';const k=document.querySelectorAll('.kpi-grid article strong');if(k[0])k[0].textContent=duration(data?.presence_seconds);if(k[1])k[1].textContent=duration(data?.no_process_seconds);if(k[2])k[2].textContent=percent(data?.norm?.combined_percent);const ac=document.querySelector('.active-process');if(ac){const h=ac.querySelector('h2');if(h)h.textContent=active?pname(active.process_code).toUpperCase():'BRAK PROCESU'}setNorm(document.querySelector('[data-norm-period="today"]'),data?.norm);setNorm(document.querySelector('[data-norm-period="month"]'),data?.monthly_norm);renderProcess(data);renderProfile(data)}
  async function loadWorker(silent=false){if(!silent)setStatus('Odczytuję bieżący stan pracownika…');const d=await api.read('mol-app-v2-worker-status');renderWorker(d);if(!silent)setStatus('Stan pracownika potwierdzony przez backend V2.','ok');return d}
  async function loadMessages(){const d=await api.read('mol-app-v2-messages',{limit:25}),p=await waitFor('[data-panel="messages"]'),items=Array.isArray(d?.items)?d.items:[];if(p){const list=p.querySelector('.message-list');if(list)list.innerHTML=items.length?items.map(x=>`<article class="mol-card message-card${x.shown_at?' is-read':''}"><span><strong>${esc(x.type||'Komunikat')}</strong><small>${esc(x.content)}</small></span><time>${x.sent_at?new Date(x.sent_at).toLocaleString('pl-PL',{timeZone:'Europe/Warsaw'}):'—'}</time></article>`).join(''):'<article class="mol-card"><small>Brak komunikatów.</small></article>'}return d}
  async function renderTeam(d){teamData=d;const p=await waitFor('[data-panel="team"]'),items=d?.items||[],list=p?.querySelector('.manager-list');if(list)list.innerHTML=items.map(r=>`<div class="manager-person"><div><b>${esc(r.employee.display_name)}</b><small>${esc(r.attendance?.state||'NOT_STARTED')} · ${esc(r.process?.process_code||'brak procesu')} · aplikacja ${esc(r.app_activity?.status||'OFFLINE')} · ES ${esc(r.es_mapping?.status||'—')}</small></div></div>`).join('')||'<p class="mol-muted">Brak osób.</p>';const rep=document.querySelector('[data-panel="manager-reports"] .mobile-report-people');if(rep)rep.innerHTML=items.map((r,i)=>`<label><input type="checkbox" value="${esc(r.employee.employee_id)}" ${i<3?'checked':''}><span><b>${esc(r.employee.display_name)}</b><small>${esc(r.employee.employee_id)}</small></span></label>`).join('')}
  async function loadManager(){const d=await api.read('mol-app-v2-leader-team',{work_date:today()});await renderTeam(d);return d}
  function lockWrites(){document.querySelectorAll('[data-action="start"],[data-action="stop"],[data-action="process-stop"],.process-option,[data-process-logout],[data-demo-correction] button,[data-mobile-message-send],.accept,.reject,.manager-create-user').forEach(b=>{b.disabled=true;b.title='Zapis biznesowy zostanie odblokowany po PASS authenticated E2E odczytów.'})}
  async function runReadE2E(){const checks=[['worker-status',()=>api.read('mol-app-v2-worker-status')],['norms-daily',()=>api.read('mol-app-v2-norms-daily')],['norms-monthly',()=>api.read('mol-app-v2-norms-monthly')],['messages',()=>api.read('mol-app-v2-messages',{limit:5})]];if(role!=='WORKER'){const team=teamData||await api.read('mol-app-v2-leader-team',{work_date:today()}),first=team?.items?.[0]?.employee?.employee_id;checks.push(['leader-team',()=>api.read('mol-app-v2-leader-team',{work_date:today()})],['report-attendance',()=>api.read('mol-app-v2-report-attendance',{date_from:today(),date_to:today()})],['report-performance',()=>api.read('mol-app-v2-report-performance',{date_from:today(),date_to:today()})],['audit-history',()=>api.read('mol-app-v2-audit-history',{date_from:today(),date_to:today(),limit:10})],['user-list',()=>api.read('mol-app-v2-user-list')],['corrections-queue',()=>api.read('mol-app-v2-corrections-queue')],['leader-message-recipients',()=>api.read('mol-app-v2-leader-message-recipients')]);if(first)checks.push(['employee-history',()=>api.read('mol-app-v2-employee-history',{employee_id:first,date_from:monthStart(),date_to:today(),limit:10})])}const failures=[];for(let i=0;i<checks.length;i++){try{await checks[i][1]()}catch(e){failures.push(`${checks[i][0]}: ${e.code||e.status||''} ${e.message}`)}setStatus(`Authenticated E2E odczytów: ${i+1}/${checks.length}${failures.length?` · błędy ${failures.length}`:''}…`,failures.length?'error':'info')}const result={at:new Date().toISOString(),role,passed:!failures.length,checks:checks.length,failures};try{sessionStorage.setItem('mol.v2.stage11.read-e2e',JSON.stringify(result))}catch{}setStatus(result.passed?`Authenticated E2E ODCZYTÓW: PASS ${checks.length}/${checks.length}. Zapisy biznesowe pozostają zablokowane.`:`Authenticated E2E ODCZYTÓW: FAIL. ${failures[0]||''}`,result.passed?'ok':'error');return result}
  async function init(){cleanBrand();try{session=await api.requireSession({surface:'mobile'});if(!session)return api.redirectLogin('session');role=String(session.user.role||'').toUpperCase();if(api.canonicalizeRole(role))return;identity();api.reveal();initialised=true;await loadWorker();await loadMessages();if(role!=='WORKER')await loadManager();lockWrites();await runReadE2E()}catch(e){if(e.status===401)return api.redirectLogin('session');setStatus(e.message||'Nie udało się uruchomić integracji.','error');api.reveal()}}
  setInterval(()=>{if(!initialised||document.hidden)return;loadWorker(true).catch(()=>{});if(role!=='WORKER')loadManager().catch(()=>{})},30000);init();
})();
