(() => {
  'use strict';
  const api=window.MOLApi; if(!api) return;
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const setStatus=(text,state='info')=>{let bar=document.querySelector('[data-live-integration-status]');if(!bar){bar=document.createElement('div');bar.dataset.liveIntegrationStatus='true';bar.style.cssText='position:sticky;top:0;z-index:90;margin:0 auto 10px;max-width:560px;padding:9px 12px;border:1px solid rgba(18,200,255,.28);border-radius:10px;background:rgba(3,20,31,.96);font:600 12px/1.35 system-ui';document.querySelector('.worker-shell')?.prepend(bar);}bar.textContent=text;bar.style.color=state==='error'?'#ff9aa4':state==='ok'?'#86f4c9':'#bfefff';bar.style.borderColor=state==='error'?'rgba(255,82,97,.65)':state==='ok'?'rgba(25,231,160,.55)':'rgba(18,200,255,.28)';};
  const localIso=(value)=>{if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toISOString();};
  const ensureActionOverlay=()=>{let overlay=document.querySelector('[data-action-overlay]');if(overlay)return overlay;overlay=document.createElement('div');overlay.className='action-overlay';overlay.dataset.actionOverlay='true';overlay.hidden=true;overlay.setAttribute('role','status');overlay.setAttribute('aria-live','assertive');overlay.setAttribute('aria-busy','true');overlay.innerHTML='<div class="action-overlay__card"><span class="action-overlay__spinner" aria-hidden="true"></span><strong data-action-overlay-title>Trwa zapis</strong><small data-action-overlay-text>Nie zamykaj aplikacji.</small></div>';document.body.append(overlay);return overlay;};
  const showActionOverlay=(title,text)=>{const overlay=ensureActionOverlay();overlay.querySelector('[data-action-overlay-title]').textContent=title;overlay.querySelector('[data-action-overlay-text]').textContent=text;overlay.hidden=false;document.body.classList.add('is-action-busy');};
  const hideActionOverlay=()=>{const overlay=document.querySelector('[data-action-overlay]');if(overlay)overlay.hidden=true;document.body.classList.remove('is-action-busy');};
  const lock=async(button,fn,busy={title:'Trwa zapis',text:'Czekamy na potwierdzenie z systemu.'})=>{if(button?.dataset.busy==='1')return;if(button){button.dataset.busy='1';button.disabled=true;}showActionOverlay(busy.title,busy.text);try{return await fn();}finally{hideActionOverlay();if(button)button.dataset.busy='0';}};
  const correctionActionable=(item)=>['PENDING','CHANGED'].includes(String(item?.status||'').toUpperCase());
  let session=null;
  const getState=()=>api.read('mol-app-v2-worker-status');
  const versionOf=(state)=>{const raw=state?.attendance_version ?? state?.attendance?.version ?? 0;const v=Number(raw);if(!Number.isInteger(v)||v<0)throw new Error('Backend nie zwrócił poprawnej wersji czasu pracy.');return v;};
  const common=async()=>{const state=await getState();return {state,body:{request_id:api.requestId(),work_date:state.work_date||today(),employee_id:session.user.employee_id,expected_version:versionOf(state)}};};
  const reload=()=>location.reload();

  function applyState(state){
    const attendance=state?.attendance?.state||'NOT_STARTED';const active=state?.active_process||null;
    const start=document.querySelector('[data-action="start"]');const stop=document.querySelector('[data-action="stop"]');const endProcess=document.querySelector('[data-action="process-stop"]');const logoutProcess=document.querySelector('[data-process-logout]');const reopen=document.querySelector('[data-action="reopen-day"]');
    if(start){start.disabled=!['NOT_STARTED','CLOSED'].includes(attendance);const title=start.querySelector('strong');const hint=start.querySelector('small');if(title)title.textContent=attendance==='CLOSED'?'Wznów pracę':'Start pracy';if(hint)hint.textContent=attendance==='CLOSED'?'Otwórz ponownie dzisiejszy dzień':'Rozpocznij zmianę';}
    if(stop)stop.disabled=attendance!=='OPEN';document.querySelectorAll('.process-option').forEach(b=>{b.disabled=attendance!=='OPEN';});if(endProcess)endProcess.disabled=attendance!=='OPEN'||!active;if(logoutProcess)logoutProcess.disabled=attendance!=='OPEN'||!active;if(reopen){reopen.hidden=true;reopen.disabled=true;}
    const form=document.querySelector('[data-worker-correction]');if(form)form.querySelectorAll('input,textarea,button').forEach(n=>{n.disabled=!state?.attendance;});
  }

  function bindAttendanceAndProcess(){
    const start=document.querySelector('[data-action="start"]');const stop=document.querySelector('[data-action="stop"]');const reopen=document.querySelector('[data-action="reopen-day"]');const endProcess=document.querySelector('[data-action="process-stop"]');const processPanel=document.querySelector('[data-panel="process"]');
    start?.addEventListener('click',e=>{e.preventDefault();lock(start,async()=>{const {state,body}=await common();const resume=state.attendance?.state==='CLOSED';setStatus(resume?'Wznawiam pracę…':'Zapisuję START pracy…');await api.write(resume?'mol-app-v2-attendance-reopen':'mol-app-v2-attendance-start',body);setStatus(resume?'Praca została wznowiona.':'START potwierdzony przez backend V2.','ok');reload();},{title:'Zapisujemy czas pracy',text:'Czekamy na potwierdzenie w Moniti. Nie klikaj ponownie.'}).catch(err=>{setStatus(err.message,'error');getState().then(applyState).catch(()=>{});});},true);
    stop?.addEventListener('click',e=>{e.preventDefault();lock(stop,async()=>{setStatus('Zapisuję STOP pracy…');const {body}=await common();await api.write('mol-app-v2-attendance-finish',body);setStatus('STOP potwierdzony przez backend V2.','ok');reload();},{title:'Kończymy pracę',text:'Czekamy na potwierdzenie STOP w Moniti.'}).catch(err=>{setStatus(err.message,'error');getState().then(applyState).catch(()=>{});});},true);
    reopen?.addEventListener('click',e=>{e.preventDefault();lock(reopen,async()=>{const {body}=await common();await api.write('mol-app-v2-attendance-reopen',body);setStatus('Praca została wznowiona.','ok');reload();},{title:'Wznawiamy pracę',text:'Czekamy na potwierdzenie w Moniti.'}).catch(err=>{setStatus(err.message,'error');getState().then(applyState).catch(()=>{});});},true);
    const processWrite=async(button,code)=>lock(button,async()=>{const {state,body}=await common();if(state.attendance?.state!=='OPEN')throw new Error('Najpierw rozpocznij dzień pracy.');const endpoint=state.active_process?'mol-app-v2-process-change':'mol-app-v2-process-start';await api.write(endpoint,{...body,process_code:code});setStatus(`Proces ${code} potwierdzony przez backend V2.`,'ok');reload();},{title:'Zapisujemy proces',text:'Czekamy na potwierdzenie zmiany. Nie klikaj ponownie.'});
    processPanel?.querySelectorAll('.process-option').forEach(button=>button.addEventListener('click',e=>{e.preventDefault();processWrite(button,button.dataset.processCode).catch(err=>{setStatus(err.message,'error');getState().then(applyState).catch(()=>{});});},true));
    const logoutProcess=processPanel?.querySelector('[data-process-logout]');const end=button=>{if(!button)return;button.addEventListener('click',e=>{e.preventDefault();lock(button,async()=>{const {state,body}=await common();if(!state.active_process)throw new Error('Nie ma aktywnego procesu.');await api.write('mol-app-v2-process-logout',body);setStatus('Proces zakończony w backendzie V2.','ok');reload();},{title:'Kończymy proces',text:'Czekamy na potwierdzenie zapisu.'}).catch(err=>{setStatus(err.message,'error');getState().then(applyState).catch(()=>{});});},true);};end(logoutProcess);end(endProcess);
  }

  function bindCorrection(){
    const form=document.querySelector('[data-worker-correction]');if(!form)return;
    form.addEventListener('submit',e=>{e.preventDefault();const button=form.querySelector('button[type="submit"]');lock(button,async()=>{const {body}=await common();const start=localIso(form.elements.start_at?.value);const stop=localIso(form.elements.stop_at?.value);const reason=String(form.elements.reason?.value||'').trim();if(!start&&!stop)throw new Error('Podaj poprawiony START lub STOP.');if(reason.length<3)throw new Error('Powód korekty musi mieć co najmniej 3 znaki.');await api.write('mol-app-v2-attendance-correct',{...body,...(start?{start_at:start}:{}),...(stop?{stop_at:stop}:{}),reason});setStatus('Korekta czasu potwierdzona przez backend V2.','ok');reload();}).catch(err=>{setStatus(err.message,'error');button.disabled=false;});},true);
  }

  async function bindWorkerMessages(){
    const panel=document.querySelector('[data-panel="messages"]');if(!panel)return;
    const data=await api.read('mol-app-v2-messages',{limit:25});const items=Array.isArray(data?.items)?data.items:[];let selected=null;let receiptQueue=Promise.resolve();let shownError=null;
    const ack=panel.querySelector('[data-message-ack]');
    const syncAck=()=>{if(!ack||!selected)return;const shown=Boolean(selected.shown_at);ack.disabled=!selected.ack_required||Boolean(selected.ack_at)||!shown;ack.textContent=selected.ack_at?'Odbiór potwierdzony':!selected.ack_required?'Potwierdzenie niewymagane':shown?'Potwierdzam odbiór':'Zapisuję wyświetlenie…';};
    panel.addEventListener('click',e=>{const card=e.target.closest('[data-live-message]');if(!card)return;selected=items.find(x=>x.message_id===card.dataset.liveMessage)||null;if(!selected)return;syncAck();if(selected.shown_at){card.classList.add('is-read');return;}const current=selected;shownError=null;receiptQueue=receiptQueue.then(()=>api.write('mol-app-v2-message-shown',{request_id:api.requestId(),message_id:current.message_id})).then(result=>{current.shown_at=result?.shown_at||new Date().toISOString();card.classList.add('is-read');if(selected===current)syncAck();}).catch(err=>{shownError=err;if(selected===current)syncAck();setStatus(err.message,'error');});},true);
    ack?.addEventListener('click',e=>{e.preventDefault();if(!selected)return;const current=selected;lock(ack,async()=>{await receiptQueue;if(!current.shown_at)throw shownError||new Error('Nie potwierdzono wyświetlenia komunikatu.');await api.write('mol-app-v2-message-ack',{request_id:api.requestId(),message_id:current.message_id});current.ack_at=new Date().toISOString();syncAck();setStatus('Odbiór komunikatu potwierdzony.','ok');}).catch(err=>{setStatus(err.message,'error');syncAck();});},true);
  }

  const selectedMobile=(root)=>root?[...root.querySelectorAll('input[type="checkbox"]:checked')].map(x=>x.value).filter(Boolean):[];
  async function bindManagerMessages(){
    const panel=document.querySelector('[data-panel="manager-messages"]');if(!panel)return;
    const allOpen=panel.querySelector('[data-mobile-message-all-open]');const content=panel.querySelector('[data-mobile-message-content]');const ack=panel.querySelector('[data-mobile-message-ack]');const send=panel.querySelector('[data-mobile-message-send]');const recipients=panel.querySelector('[data-mobile-message-recipients]');const count=panel.querySelector('[data-mobile-message-count]');const length=panel.querySelector('[data-mobile-message-length]');if(!recipients||!content||!send)return;
    const sync=()=>{const ids=selectedMobile(recipients);recipients.querySelectorAll('input').forEach(x=>x.disabled=Boolean(allOpen?.checked));const selectAll=panel.querySelector('[data-mobile-message-select-all]');const clear=panel.querySelector('[data-mobile-message-clear]');if(selectAll)selectAll.disabled=Boolean(allOpen?.checked);if(clear)clear.disabled=Boolean(allOpen?.checked);if(count)count.textContent=allOpen?.checked?'Wszyscy aktualnie OPEN':`Wybrano ${ids.length}`;if(length)length.textContent=String(content.value.length);send.disabled=!content.value.trim()||(!allOpen?.checked&&!ids.length);};
    [allOpen,content,ack].forEach(n=>{if(n)n.disabled=false;});recipients.querySelectorAll('input').forEach(n=>n.disabled=false);const selectAll=panel.querySelector('[data-mobile-message-select-all]');const clear=panel.querySelector('[data-mobile-message-clear]');if(selectAll)selectAll.disabled=false;if(clear)clear.disabled=false;allOpen?.addEventListener('change',sync);content.addEventListener('input',sync);recipients.addEventListener('change',sync);selectAll?.addEventListener('click',()=>{recipients.querySelectorAll('input').forEach(x=>x.checked=true);sync();});clear?.addEventListener('click',()=>{recipients.querySelectorAll('input').forEach(x=>x.checked=false);sync();});
    send.addEventListener('click',e=>{e.preventDefault();lock(send,async()=>{const ids=selectedMobile(recipients);const body={request_id:api.requestId(),content:content.value.trim(),ack_required:Boolean(ack?.checked),...(allOpen?.checked?{all_open:true}:{recipient_ids:ids})};await api.write('mol-app-v2-leader-message',body);content.value='';setStatus('Komunikat wysłany przez backend V2.','ok');sync();}).catch(err=>{setStatus(err.message,'error');sync();});},true);sync();
  }

  async function approveQueuedCorrection(item){
    if(!item?.correction_id)throw new Error('Brak correction_id korekty.');
    const preview=await api.write('mol-app-v2-correction-preview',{correction_id:item.correction_id});
    const approvedHash=String(preview?.approved_hash||'');
    if(!/^[0-9a-f]{64}$/i.test(approvedHash))throw new Error('Backend nie zwrócił approved_hash korekty.');
    return api.write('mol-app-v2-correction-approve',{correction_id:item.correction_id,request_id:item.correction_id,approved_hash:approvedHash});
  }

  async function bindCorrections(){
    const panel=document.querySelector('[data-panel="manager-corrections"]');if(!panel)return;
    const data=await api.read('mol-app-v2-corrections-queue');const items=Array.isArray(data?.items)?data.items:[];const rows=[...panel.querySelectorAll('.correction-item')];
    rows.forEach((row,i)=>{const item=items[i];if(!item)return;const accept=row.querySelector('.accept');const reject=row.querySelector('.reject');const actionable=correctionActionable(item);if(accept){accept.disabled=!actionable;accept.textContent=actionable?'Akceptuj':'Brak akcji';if(actionable)accept.addEventListener('click',e=>{e.preventDefault();lock(accept,async()=>{await approveQueuedCorrection(item);setStatus('Korekta zatwierdzona przez bezpieczną ścieżkę preview → approve.','ok');reload();}).catch(err=>{setStatus(err.message,'error');accept.disabled=false;});},true);}if(reject){reject.disabled=!actionable;reject.textContent=actionable?'Odrzuć':'Zamknięta';if(actionable)reject.addEventListener('click',e=>{e.preventDefault();lock(reject,async()=>{await api.write('mol-app-v2-correction-reject',{request_id:api.requestId(),correction_id:item.correction_id});setStatus('Korekta odrzucona.','ok');reload();}).catch(err=>{setStatus(err.message,'error');reject.disabled=false;});},true);}});
  }

  function addUserAction(article,label,handler){const button=document.createElement('button');button.className='mol-button';button.type='button';button.textContent=label;button.addEventListener('click',handler);article.append(button);return button;}

  async function bindUsers(){
    const panel=document.querySelector('[data-panel="manager-users"]');if(!panel)return;
    const data=await api.read('mol-app-v2-user-list');const items=Array.isArray(data?.items)?data.items:[];const articles=[...panel.querySelectorAll('.manager-user-list article')];const actor=session.user;
    articles.forEach((article,i)=>{const user=items[i];if(!user)return;article.querySelectorAll('button').forEach(b=>b.remove());const actionStart=article.children.length;
      const canToggle=actor.role==='ADMIN'?user.employee_id!==actor.employee_id:user.role==='WORKER';
      if(canToggle){const toggle=addUserAction(article,user.active?'Dezaktywuj':'Aktywuj',e=>{e.preventDefault();lock(toggle,async()=>{await api.write('mol-app-v2-user-active',{request_id:api.requestId(),employee_id:user.employee_id,active:!user.active});setStatus('Stan konta zmieniony w backendzie V2.','ok');reload();}).catch(err=>{setStatus(err.message,'error');toggle.disabled=false;});});}
      if(user.can_reset_password===true){const reset=addUserAction(article,'Reset hasła',e=>{e.preventDefault();const pwd=prompt(`Nowe hasło dla ${user.display_name}:`);if(!pwd)return;lock(reset,async()=>{await api.write('mol-app-v2-user-password-reset',{request_id:api.requestId(),employee_id:user.employee_id,new_password:pwd});setStatus('Hasło zostało zresetowane.','ok');reset.disabled=false;}).catch(err=>{setStatus(err.message,'error');reset.disabled=false;});});}
      if(article.children.length===actionStart){const note=document.createElement('small');note.className='mol-muted';note.textContent='Brak dostępnych akcji dla tej roli.';article.append(note);}
    });
    const form=panel.querySelector('[data-manager-user-create]');if(form){const roles=actor.role==='ADMIN'?['WORKER','LEADER','ADMIN']:['WORKER'];const select=form.elements.role;if(select)select.replaceChildren(...roles.map(r=>{const o=document.createElement('option');o.value=r;o.textContent=r;return o;}));form.querySelectorAll('input,select,button').forEach(n=>n.disabled=false);form.addEventListener('submit',e=>{e.preventDefault();const b=form.querySelector('button[type="submit"]');lock(b,async()=>{const fd=new FormData(form);const body={request_id:api.requestId(),login:String(fd.get('login')||'').trim(),display_name:String(fd.get('display_name')||'').trim(),initial_password:String(fd.get('initial_password')||''),role:String(fd.get('role')||''),moniti_worker_id:String(fd.get('moniti_worker_id')||'').trim(),es_worker_id:String(fd.get('es_worker_id')||'').trim()};await api.write('mol-app-v2-user-create',body);setStatus('Użytkownik utworzony w backendzie V2.','ok');reload();}).catch(err=>{setStatus(err.message,'error');b.disabled=false;});},true);}
  }

  async function init(){
    try{await window.MOLLiveReady;session=await api.requireSession({surface:'mobile'});if(!session)return api.redirectLogin('session');const state=await getState();applyState(state);bindAttendanceAndProcess();bindCorrection();const optionalActions=[bindWorkerMessages()];if(['LEADER','ADMIN'].includes(session.user.role))optionalActions.push(bindManagerMessages(),bindCorrections(),bindUsers());const results=await Promise.allSettled(optionalActions);const failures=results.filter(result=>result.status==='rejected');if(failures.length)setStatus(`Podstawowe akcje działają. Nie uruchomiono ${failures.length} opcjonalnych sekcji.`,'error');else setStatus('Integracja LIVE gotowa. Odczyty i przyciski są podłączone do backendu V2.','ok');}
    catch(error){setStatus(`Nie udało się uruchomić części akcji: ${error.message}`,'error');}
  }
  init();
})();
