(() => {
  'use strict';
  const shell=document.querySelector('.worker-shell'); if(!shell) return;
  const role=window.MOLRoles.normalizeRole(new URLSearchParams(location.search).get('role')||'WORKER');
  const capabilities=window.MOLRoles.get(role); if(!capabilities?.managerMobile) return;
  const css=document.createElement('link'); css.rel='stylesheet'; css.href='./manager.css'; document.head.append(css);
  const team=document.querySelector('[data-panel="team"]'); const bottom=document.querySelector('.bottom-nav'); if(!team||!bottom) return;
  const actions=document.createElement('div'); actions.className='manager-actions'; actions.innerHTML='<button class="mol-button" data-manager-target="manager-reports">Raporty</button><button class="mol-button" data-manager-target="manager-messages">Komunikaty</button><button class="mol-button" data-manager-target="manager-corrections">Korekty</button><button class="mol-button" data-manager-target="manager-users">Użytkownicy</button>'; team.append(actions);
  const mk=(name,html)=>{const s=document.createElement('section');s.className='screen-placeholder manager-mobile manager-detail';s.dataset.panel=name;s.hidden=true;s.innerHTML=`<button class="manager-back" type="button">← Zespół</button>${html}`;shell.insertBefore(s,bottom);return s;};
  const reports=mk('manager-reports',`<p class="mol-kicker">LEADER / ADMIN</p><h2>Raport wydajności</h2><div class="manager-filter mol-card"><label>Od <input data-mobile-report-from type="date"></label><label>Do <input data-mobile-report-to type="date"></label></div><section class="mol-card mobile-report-selector"><div class="mobile-report-head"><div><small>Pracownicy do raportu</small><strong data-mobile-report-count>Wybrano 0</strong></div><div><button type="button" data-mobile-report-all>Wszyscy</button><button type="button" data-mobile-report-clear>Wyczyść</button></div></div><div class="mobile-report-people"><p class="mol-muted">Ładowanie pracowników z backendu V2…</p></div><button class="mol-button mol-button--primary" type="button" data-mobile-report-generate disabled>Generuj raport</button></section><div class="manager-mobile-grid"><article class="mol-card"><small>Wybrani</small><strong data-mobile-report-selected>0</strong></article><article class="mol-card"><small>PICK/PAK grupy · ważone</small><strong data-mobile-report-norm>—</strong></article></div><div class="mol-card manager-report-list" data-mobile-report-list><p class="mol-muted">Brak wygenerowanego raportu.</p></div><div class="manager-actions"><button class="mol-button" data-mobile-export="CSV" disabled>CSV</button><button class="mol-button mol-button--primary" data-mobile-export="XLSX" disabled>XLSX</button></div>`);
  const messages=mk('manager-messages',`<p class="mol-kicker">Komunikacja</p><h2>Wyślij komunikat</h2><section class="mol-card mobile-message-composer"><label class="mobile-message-all"><input type="checkbox" data-mobile-message-all-open disabled><span><b>Wszyscy aktualnie w pracy</b><small>Backend zamrozi listę odbiorców przy wysłaniu.</small></span></label><div class="mobile-report-head"><div><small>Odbiorcy</small><strong data-mobile-message-count>Wybrano 0</strong></div><div><button type="button" data-mobile-message-select-all disabled>Wszyscy</button><button type="button" data-mobile-message-clear disabled>Wyczyść</button></div></div><div class="mobile-report-people" data-mobile-message-recipients><p class="mol-muted">Ładowanie odbiorców z backendu V2…</p></div><label class="mobile-message-content">Treść<textarea rows="5" maxlength="2000" data-mobile-message-content disabled></textarea><small><span data-mobile-message-length>0</span>/2000</small></label><label class="mobile-message-all"><input type="checkbox" data-mobile-message-ack disabled><span><b>Wymagaj potwierdzenia odbioru</b></span></label><button class="mol-button mol-button--primary" type="button" data-mobile-message-send disabled>Wyślij komunikat</button><p class="mol-muted" data-mobile-message-status>Weryfikacja odczytów V2…</p></section>`);
  const corrections=mk('manager-corrections','<p class="mol-kicker">Decyzje</p><h2>Korekty</h2><div class="manager-correction-list"><p class="mol-muted">Ładowanie korekt z backendu V2…</p></div>');
  const allowedRoles=(capabilities.userCreateRoles||[]).join(' / ');
  const users=mk('manager-users',`<p class="mol-kicker">Administracja · ${role}</p><h2>Użytkownicy</h2><div class="mol-card manager-user-policy"><small>Możesz tworzyć role</small><strong>${allowedRoles}</strong></div><div class="manager-user-list"><p class="mol-muted">Ładowanie kont z backendu V2…</p></div><form class="mol-card correction-form" data-manager-user-create style="padding:14px;margin-top:12px"><label>Login<input name="login" disabled></label><label>Nazwa<input name="display_name" disabled></label><label>Hasło początkowe<input name="initial_password" type="password" disabled></label><label>Rola<select name="role" disabled>${(capabilities.userCreateRoles||[]).map(r=>`<option value="${r}">${r}</option>`).join('')}</select></label><label>Moniti worker ID<input name="moniti_worker_id" disabled></label><label>ES worker ID<input name="es_worker_id" disabled></label><button class="mol-button mol-button--primary manager-create-user" type="submit" disabled>Dodaj użytkownika</button></form>`);
  [reports,messages,corrections,users].forEach((panel)=>panel.querySelector('.manager-back')?.addEventListener('click',()=>window.MOLMobileShow?.('team')));
  actions.querySelectorAll('[data-manager-target]').forEach((button)=>button.addEventListener('click',()=>window.MOLMobileShow?.(button.dataset.managerTarget)));
})();
