(() => {
  'use strict';
  const api=window.MOLApi;if(!api)return;
  let session=null,busy=false;
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const yesterday=()=>{const d=new Date();d.setDate(d.getDate()-1);return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);};
  const clock=v=>v?new Date(v).toLocaleTimeString('pl-PL',{timeZone:'Europe/Warsaw',hour:'2-digit',minute:'2-digit'}):'';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function enable(){document.querySelectorAll('[data-process-action="change-hours"]').forEach(b=>{b.disabled=busy;b.title='Zmień własne godziny za dziś lub wczoraj';const small=b.querySelector('small');if(small)small.textContent='Możesz zmienić START/STOP za dziś lub wczoraj · lider dostanie informację';});}
  async function open(){if(busy)return;session=session||await api.requireSession({surface:'mobile'});const user=session?.user||{};if(!user.employee_id)return;let current={};try{current=await api.request('mol-app-v3-worker-status',{timeoutMs:6000})||{};}catch{}
    const att=current.attendance||{},back=document.createElement('div');back.className='worktime-mobile-backdrop';back.innerHTML=`<section class="worktime-mobile-modal" role="dialog" aria-modal="true"><p class="mol-kicker">Korekta czasu pracy</p><h2>Zmień godziny pracy</h2><p>Możesz poprawić własny czas za dziś albo wczoraj. Zmiana nie wymaga akceptacji, ale liderzy dostaną informację.</p><label>Dzień<select data-wt-day><option value="${today()}">Dzisiaj</option><option value="${yesterday()}">Wczoraj</option></select></label><label>START<input data-wt-start type="time" step="60" value="${esc(clock(att.start_at))}" required></label><label>STOP <small>(dla dzisiaj może zostać puste, jeśli nadal pracujesz)</small><input data-wt-stop type="time" step="60" value="${esc(clock(att.stop_at))}"></label><label>Powód<input data-wt-reason type="text" maxlength="200" value="Korekta godzin pracy"></label><p class="worktime-mobile-error" data-wt-error></p><div class="worktime-mobile-actions"><button class="mol-button" data-wt-cancel>Anuluj</button><button class="mol-button mol-button--primary" data-wt-save>Zapisz zmianę</button></div></section>`;document.body.append(back);
    const close=()=>back.remove(),day=back.querySelector('[data-wt-day]'),start=back.querySelector('[data-wt-start]'),stop=back.querySelector('[data-wt-stop]'),err=back.querySelector('[data-wt-error]'),save=back.querySelector('[data-wt-save]');
    day.addEventListener('change',()=>{if(day.value===today()){start.value=clock(att.start_at);stop.value=clock(att.stop_at);}else{start.value='';stop.value='';}});back.querySelector('[data-wt-cancel]').addEventListener('click',close);back.addEventListener('click',e=>{if(e.target===back)close();});
    save.addEventListener('click',async()=>{if(!/^\d{2}:\d{2}$/.test(start.value)){err.textContent='Podaj godzinę START.';return;}if(day.value===yesterday()&&!/^\d{2}:\d{2}$/.test(stop.value)){err.textContent='Dla wczoraj podaj również STOP.';return;}busy=true;save.disabled=true;enable();err.textContent='Zapisywanie w Moniti…';try{await api.write('mol-app-v3-worktime-change',{request_id:api.requestId(),employee_id:user.employee_id,work_date:day.value,start_time:start.value,stop_time:stop.value||null,reason:back.querySelector('[data-wt-reason]').value.trim()||'Korekta godzin pracy'});close();location.reload();}catch(e){err.textContent=e?.message||'Nie udało się zapisać zmiany.';busy=false;save.disabled=false;enable();}});start.focus();
  }
  document.addEventListener('click',e=>{const b=e.target.closest('[data-process-action="change-hours"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();open().catch(()=>{});},true);
  const style=document.createElement('style');style.textContent='.worktime-mobile-backdrop{position:fixed;inset:0;z-index:15000;display:grid;place-items:center;background:rgba(0,0,0,.78);padding:16px}.worktime-mobile-modal{width:min(500px,100%);max-height:92vh;overflow:auto;background:#07131d;color:#eef8ff;border:1px solid rgba(18,200,255,.3);border-radius:18px;padding:20px}.worktime-mobile-modal label{display:grid;gap:7px;margin:14px 0}.worktime-mobile-modal input,.worktime-mobile-modal select{padding:12px;border-radius:10px;border:1px solid rgba(255,255,255,.16);background:#031019;color:#fff;font:inherit}.worktime-mobile-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.worktime-mobile-error{color:#ff9da5;min-height:1.3em}';document.head.append(style);setInterval(enable,700);enable();
})();
