(() => {
  'use strict';
  const api=window.MOLApi;if(!api)return;
  const view=document.querySelector('[data-view="leader-messages"]');if(!view)return;
  const css=document.createElement('style');css.textContent=`.v3c-grid{display:grid;grid-template-columns:minmax(420px,1.15fr) minmax(360px,.85fr);gap:16px}.v3c-card{padding:18px}.v3c-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.v3c-recipients{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:8px;max-height:220px;overflow:auto;margin:10px 0 14px}.v3c-rec{display:flex;gap:8px;align-items:center;padding:9px;border:1px solid rgba(255,255,255,.1);border-radius:10px}.v3c-text{width:100%;min-height:130px;resize:vertical}.v3c-actions{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:10px}.v3c-list{display:grid;gap:10px;max-height:520px;overflow:auto}.v3c-msg{padding:11px;border:1px solid rgba(255,255,255,.1);border-radius:10px;background:rgba(255,255,255,.03)}.v3c-msg[data-open="true"]{border-color:rgba(255,188,64,.5)}.v3c-msg h3{margin:0 0 4px;font-size:14px}.v3c-msg p{margin:0 0 7px;line-height:1.4}.v3c-msg small{opacity:.7}.v3c-msg button{margin-top:8px}.v3c-history-controls{display:flex;gap:8px;align-items:center;margin-bottom:10px}.v3c-history-controls select{flex:1}.v3c-muted{opacity:.7;font-size:13px}@media(max-width:1050px){.v3c-grid{grid-template-columns:1fr}}`;document.head.append(css);
  view.innerHTML=`<div class="page-title"><div><p class="mol-kicker">Etap 5 · V3</p><h1>Alerty i komunikaty</h1><small>Lekki polling V3. Push APK nie jest w tym etapie wdrożony.</small></div><span class="mol-chip mol-chip--info">LIVE V3</span></div><div class="v3c-grid"><section class="mol-card v3c-card"><div class="v3c-title"><div><p class="mol-kicker">Nowy komunikat</p><h2>Wyślij do pracownika</h2></div><small>ACK wymagany</small></div><label class="all-open-toggle"><input type="checkbox" data-v3c-all><span><b>Wszyscy pracownicy aktualnie w pracy</b><small>Lista odbiorców jest ustalana po stronie backendu.</small></span></label><div class="v3c-recipients" data-v3c-recipients><p class="v3c-muted">Ładowanie odbiorców…</p></div><textarea class="v3c-text" data-v3c-text maxlength="2000" placeholder="Treść komunikatu"></textarea><div class="v3c-actions"><small data-v3c-status>0/2000</small><button class="mol-button mol-button--primary" data-v3c-send disabled>Wyślij komunikat</button></div></section><section class="mol-card v3c-card"><div class="v3c-title"><div><p class="mol-kicker">Moja skrzynka</p><h2>Alerty dla lidera</h2></div><span class="mol-chip mol-chip--info" data-v3c-owncount>0</span></div><div class="v3c-list" data-v3c-own><p class="v3c-muted">Ładowanie…</p></div></section><section class="mol-card v3c-card" style="grid-column:1/-1"><div class="v3c-title"><div><p class="mol-kicker">Historia</p><h2>Historia komunikacji pracownika</h2></div><small>25 rekordów / strona</small></div><div class="v3c-history-controls"><select data-v3c-history-person><option value="">Wybierz pracownika…</option></select><button class="mol-button" data-v3c-refresh>Odśwież</button></div><div class="v3c-list" data-v3c-history><p class="v3c-muted">Wybierz pracownika.</p></div></section></div>`;
  const $=s=>view.querySelector(s),recBox=$('[data-v3c-recipients]'),all=$('[data-v3c-all]'),text=$('[data-v3c-text]'),send=$('[data-v3c-send]'),status=$('[data-v3c-status]'),own=$('[data-v3c-own]'),ownCount=$('[data-v3c-owncount]'),person=$('[data-v3c-history-person]'),history=$('[data-v3c-history]'),refresh=$('[data-v3c-refresh]');
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const labels={NO_PROCESS:'Brak procesu',NO_ACTIVITY:'Brak aktywności',WRONG_PROCESS:'Niezgodny proces',WORK_OUTSIDE_APP:'Praca poza aplikacją',ATTENDANCE_CORRECTION:'Korekta czasu pracy',FORGOTTEN_STOP:'Brak STOP',MANUAL:'Komunikat ręczny'};
  let recipients=[],stopped=false;
  const checked=()=>[...recBox.querySelectorAll('input:checked')].map(x=>x.value);
  function sync(){recBox.querySelectorAll('input').forEach(x=>x.disabled=all.checked);const n=checked().length;send.disabled=!text.value.trim()||(!all.checked&&!n);status.textContent=`${text.value.length}/2000 · ${all.checked?'wszyscy w pracy':`wybrano ${n}`}`;}
  function cards(items,allowAck=false){if(!items?.length)return '<p class="v3c-muted">Brak komunikatów.</p>';return items.map(m=>`<article class="v3c-msg" data-open="${m.cause_status==='OPEN'}"><h3>${esc(labels[m.type]||m.type)}</h3><p>${esc(m.content)}</p><small>${m.cause_status==='RESOLVED'?'Rozwiązany':m.ack_at?'Potwierdzony':m.shown_at?'Wyświetlony':'Oczekuje'} · ${esc(new Date(m.sent_at).toLocaleString('pl-PL'))}</small>${allowAck&&m.ack_required&&!m.ack_at?`<button class="mol-button mol-button--primary" data-v3c-ack="${esc(m.message_id)}">Potwierdzam</button>`:''}</article>`).join('');}
  async function loadRecipients(){const d=await api.read('mol-app-v3-comm-recipients');recipients=Array.isArray(d?.items)?d.items:[];recBox.innerHTML=recipients.length?recipients.map(r=>`<label class="v3c-rec"><input type="checkbox" value="${esc(r.employee_id)}"><span>${esc(r.display_name)}</span></label>`).join(''):'<p class="v3c-muted">Brak pracowników z rozpoczętym dniem pracy.</p>';person.innerHTML='<option value="">Wybierz pracownika…</option>'+recipients.map(r=>`<option value="${esc(r.employee_id)}">${esc(r.display_name)}</option>`).join('');sync();}
  async function loadOwn(){const d=await api.read('mol-app-v3-comm-list',{limit:25});const items=d?.items||[];own.innerHTML=cards(items,true);ownCount.textContent=String(d?.unacknowledged_count||0);for(const m of items.filter(x=>!x.shown_at)){try{await api.write('mol-app-v3-comm-shown',{request_id:api.requestId(),message_id:m.message_id});}catch{}}}
  async function loadHistory(){if(!person.value){history.innerHTML='<p class="v3c-muted">Wybierz pracownika.</p>';return;}history.innerHTML='<p class="v3c-muted">Ładowanie…</p>';try{const d=await api.read('mol-app-v3-comm-list',{employee_id:person.value,limit:25});history.innerHTML=cards(d?.items||[],false);}catch(e){history.innerHTML=`<p class="v3c-muted">${esc(e.message)}</p>`;}}
  send.addEventListener('click',async()=>{send.disabled=true;try{await api.write('mol-app-v3-comm-send',{request_id:api.requestId(),content:text.value.trim(),...(all.checked?{all_open:true}:{recipient_ids:checked()}),ack_required:true});text.value='';all.checked=false;recBox.querySelectorAll('input').forEach(x=>x.checked=false);status.textContent='Komunikat wysłany przez V3.';await loadHistory();}catch(e){status.textContent=e.message||'Błąd wysyłki.';}finally{sync();}});
  own.addEventListener('click',async e=>{const b=e.target.closest('[data-v3c-ack]');if(!b)return;b.disabled=true;try{await api.write('mol-app-v3-comm-ack',{request_id:api.requestId(),message_id:b.dataset.v3cAck});await loadOwn();}catch(err){b.disabled=false;status.textContent=err.message||'Błąd ACK.';}});
  all.addEventListener('change',sync);text.addEventListener('input',sync);recBox.addEventListener('change',sync);person.addEventListener('change',loadHistory);refresh.addEventListener('click',loadHistory);
  async function init(){try{await api.requireSession({surface:'web'});await loadRecipients();await loadOwn();sync();}catch(e){if(e.status===401||e.status===403)stopped=true;own.innerHTML=`<p class="v3c-muted">${esc(e.message)}</p>`;}}
  init();const timer=setInterval(()=>{if(!stopped&&document.visibilityState==='visible')loadOwn().catch(()=>{});},20000);window.addEventListener('pagehide',()=>clearInterval(timer));
})();
