(() => {
  'use strict';
  const api=window.MOLApi, view=document.querySelector('[data-view="users"]');
  if(!api||!view)return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const roleLabel=r=>({WORKER:'Pracownik',LEADER:'Lider',ADMIN:'Administrator'})[r]||r;
  let data={items:[],actor_role:'LEADER'},filter='ALL';

  const style=document.createElement('style');
  style.textContent=`
  .usr-page{display:grid;gap:16px}.usr-head{display:flex;justify-content:space-between;gap:16px;align-items:center}.usr-head h1{margin:4px 0}.usr-actions,.usr-filters,.usr-row-actions{display:flex;gap:9px;flex-wrap:wrap}.usr-filters input,.usr-filters select,.usr-form input,.usr-form select{min-height:40px;padding:9px 11px;border:1px solid var(--mol-border);border-radius:9px;background:#031019;color:var(--mol-text);font:inherit}.usr-card{padding:0;overflow:hidden}.usr-table-wrap{overflow:auto}.usr-table{width:100%;border-collapse:collapse;min-width:980px}.usr-table th,.usr-table td{padding:12px;border-bottom:1px solid rgba(81,178,220,.11);text-align:left;font-size:12px}.usr-table th{color:var(--mol-text-muted);font-size:10px;text-transform:uppercase}.usr-table small{display:block;color:var(--mol-text-muted);margin-top:3px}.usr-pill{display:inline-flex;padding:5px 8px;border-radius:999px;font-weight:800;font-size:10px}.usr-pill.on,.usr-pill.ok{color:var(--mol-green);background:rgba(34,210,162,.1)}.usr-pill.off{color:#aeb9c3;background:rgba(255,255,255,.06)}.usr-pill.warn{color:var(--mol-yellow);background:rgba(255,188,64,.1)}.usr-row-actions button{padding:7px 9px}.usr-empty{text-align:center!important;padding:32px!important;color:var(--mol-text-muted)}.usr-modal-bg{position:fixed;inset:0;z-index:14000;display:grid;place-items:center;padding:20px;background:rgba(0,0,0,.76)}.usr-modal{width:min(560px,100%);max-height:90vh;overflow:auto;padding:22px;border:1px solid rgba(18,200,255,.3);border-radius:18px;background:#07131d;color:var(--mol-text)}.usr-form{display:grid;gap:12px}.usr-form label{display:grid;gap:6px;color:var(--mol-text-muted);font-size:11px}.usr-modal-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:18px}.usr-error{min-height:20px;color:#ff9aa4}.usr-note{padding:10px;border-radius:9px;background:rgba(18,200,255,.06);color:var(--mol-text-muted);font-size:12px;line-height:1.5}@media(max-width:700px){.usr-head{align-items:flex-start;flex-direction:column}}
  `;document.head.append(style);

  view.innerHTML=`<div class="usr-page">
    <header class="usr-head"><div><p class="mol-kicker">Administracja V3</p><h1>Użytkownicy</h1><small>Nieaktywne konta nie pojawiają się w bieżącej pracy, ale pozostają w raportach historycznych.</small></div><button class="mol-button mol-button--primary" type="button" data-usr-add>＋ Dodaj użytkownika</button></header>
    <div class="usr-filters"><input type="search" data-usr-search placeholder="Szukaj nazwy, loginu lub MOL…"><select data-usr-filter><option value="ALL">Wszyscy</option><option value="ACTIVE">Aktywni</option><option value="INACTIVE">Nieaktywni</option></select><button class="mol-button" type="button" data-usr-refresh>Odśwież</button></div>
    <section class="mol-card usr-card"><div class="usr-table-wrap"><table class="usr-table"><thead><tr><th>Użytkownik</th><th>Login / rola</th><th>Status</th><th>Moniti</th><th>EasyStorage</th><th>Akcje</th></tr></thead><tbody data-usr-body><tr><td colspan="6" class="usr-empty">Ładowanie…</td></tr></tbody></table></div></section>
  </div>`;

  const body=view.querySelector('[data-usr-body]'), search=view.querySelector('[data-usr-search]');
  const mapping=(value,name)=>value?`<span class="usr-pill ok">ZMAPOWANO</span><small>${esc(value)}</small>`:`<span class="usr-pill warn">WYMAGA MAPOWANIA</span><small>${esc(name)}</small>`;
  function render(){
    const q=search.value.trim().toLocaleLowerCase('pl');
    const items=data.items.filter(u=>(filter==='ALL'||(filter==='ACTIVE')===u.active)&&(!q||`${u.display_name} ${u.login} ${u.employee_id}`.toLocaleLowerCase('pl').includes(q)));
    body.innerHTML=items.map(u=>`<tr data-id="${esc(u.employee_id)}"><td><b>${esc(u.display_name)}</b><small>${esc(u.employee_id)}</small></td><td>${esc(u.login)}<small>${esc(roleLabel(u.role))}</small></td><td><span class="usr-pill ${u.active?'on':'off'}">${u.active?'AKTYWNY':'NIEAKTYWNY'}</span></td><td>${mapping(u.moniti_worker_id,'brak jednoznacznego pracownika')}</td><td>${mapping(u.es_worker_id,'brak jednoznacznego operatora')}</td><td><div class="usr-row-actions"><button class="mol-button" data-act="toggle">${u.active?'Dezaktywuj':'Aktywuj'}</button>${u.can_reset_password?'<button class="mol-button" data-act="password">Hasło</button>':''}${data.actor_role==='ADMIN'&&!u.active?'<button class="mol-button" data-act="delete">Usuń</button>':''}</div></td></tr>`).join('')||'<tr><td colspan="6" class="usr-empty">Brak użytkowników dla wybranego filtra.</td></tr>';
  }
  async function refresh(){body.innerHTML='<tr><td colspan="6" class="usr-empty">Ładowanie…</td></tr>';data=await api.read('mol-app-v3-user-list');render();window.MOLRefreshReportPeople?.();return data;}
  function modal(html){const bg=document.createElement('div');bg.className='usr-modal-bg';bg.innerHTML=`<section class="usr-modal" role="dialog" aria-modal="true">${html}</section>`;document.body.append(bg);const close=()=>bg.remove();bg.addEventListener('click',e=>{if(e.target===bg)close()});bg.querySelector('[data-cancel]')?.addEventListener('click',close);return{bg,close};}
  function openAdd(){const roles=data.actor_role==='ADMIN'?'<option value="WORKER">Pracownik</option><option value="LEADER">Lider</option><option value="ADMIN">Administrator</option>':'<option value="WORKER">Pracownik</option>';const m=modal(`<p class="mol-kicker">Nowe konto</p><h2>Dodaj użytkownika</h2><form class="usr-form" data-form><label>Imię i nazwisko<input name="display_name" required maxlength="100"></label><label>Login<input name="login" required minlength="3" maxlength="64" pattern="[a-zA-Z0-9._-]+"></label><label>Hasło początkowe<input name="password" type="password" required minlength="8" maxlength="128"></label><label>Rola<select name="role">${roles}</select></label><p class="usr-note">Identyfikator MOL zostanie nadany automatycznie. Moniti i EasyStorage zostaną dopasowane przez system tylko przy jednym jednoznacznym wyniku.</p><div class="usr-error" data-error></div><div class="usr-modal-actions"><button class="mol-button" type="button" data-cancel>Anuluj</button><button class="mol-button mol-button--primary" type="submit">Dodaj</button></div></form>`);const form=m.bg.querySelector('[data-form]');form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form),err=form.querySelector('[data-error]'),save=form.querySelector('[type="submit"]');save.disabled=true;err.textContent='Tworzę konto i sprawdzam mapowania…';try{const result=await api.write('mol-app-v3-user-create',{request_id:api.requestId(),display_name:fd.get('display_name'),login:fd.get('login'),initial_password:fd.get('password'),role:fd.get('role')});m.close();await refresh();const es=result?.mapping?.easy_storage,moniti=result?.mapping?.moniti;if(es!=='MAPPED'||moniti!=='MAPPED')alert(`Konto utworzone. Mapowanie: Moniti ${moniti||'—'}, EasyStorage ${es||'—'}.`);}catch(x){err.textContent=x.message||'Nie udało się utworzyć konta.';save.disabled=false;}});}
  async function toggle(u){if(!confirm(`${u.active?'Dezaktywować':'Aktywować'} konto ${u.display_name}?`))return;await api.write('mol-app-v3-user-active',{request_id:api.requestId(),employee_id:u.employee_id,active:!u.active});await refresh();}
  function password(u){const m=modal(`<p class="mol-kicker">Bezpieczeństwo</p><h2>Ustaw nowe hasło</h2><p>${esc(u.display_name)} · ${esc(u.employee_id)}</p><form class="usr-form" data-form><label>Nowe hasło<input name="password" type="password" required minlength="8" maxlength="128"></label><div class="usr-error" data-error></div><div class="usr-modal-actions"><button class="mol-button" type="button" data-cancel>Anuluj</button><button class="mol-button mol-button--primary" type="submit">Zapisz</button></div></form>`);const form=m.bg.querySelector('[data-form]');form.addEventListener('submit',async e=>{e.preventDefault();const err=form.querySelector('[data-error]'),save=form.querySelector('[type="submit"]');save.disabled=true;try{await api.write('mol-app-v3-user-password-reset',{request_id:api.requestId(),employee_id:u.employee_id,new_password:new FormData(form).get('password')});m.close();alert('Hasło zmienione. Aktywne sesje użytkownika zostały zakończone.');}catch(x){err.textContent=x.message||'Nie udało się zmienić hasła.';save.disabled=false;}});}
  async function remove(u){if(!confirm(`Trwale usunąć konto ${u.display_name}? Operacja powiedzie się tylko wtedy, gdy konto nie ma historii.`))return;try{await api.write('mol-app-v3-user-delete',{request_id:api.requestId(),employee_id:u.employee_id});await refresh();}catch(x){alert(x.message||'Nie udało się usunąć konta.');}}
  body.addEventListener('click',e=>{const btn=e.target.closest('[data-act]'),row=e.target.closest('[data-id]');if(!btn||!row)return;const u=data.items.find(x=>x.employee_id===row.dataset.id);if(!u)return;const p=btn.dataset.act==='toggle'?toggle(u):btn.dataset.act==='password'?password(u):remove(u);Promise.resolve(p).catch(x=>alert(x.message||'Operacja nie powiodła się.'));});
  view.querySelector('[data-usr-add]').addEventListener('click',openAdd);
  view.querySelector('[data-usr-refresh]').addEventListener('click',()=>refresh().catch(x=>{body.innerHTML=`<tr><td colspan="6" class="usr-empty">${esc(x.message)}</td></tr>`;}));
  view.querySelector('[data-usr-filter]').addEventListener('change',e=>{filter=e.target.value;render()});
  search.addEventListener('input',render);
  document.querySelector('.sidebar [data-section="users"]')?.addEventListener('click',()=>refresh().catch(()=>{}));
  window.MOLUsers=Object.freeze({refresh,get items(){return data.items;},get actorRole(){return data.actor_role;}});
  refresh().catch(x=>{body.innerHTML=`<tr><td colspan="6" class="usr-empty">${esc(x.message)}</td></tr>`;});
})();