(() => {
  'use strict';
  const form=document.querySelector('[data-auth-form]'),password=document.querySelector('[data-auth-password]'),toggle=document.querySelector('[data-auth-toggle]'),message=document.querySelector('[data-auth-message]'),submit=form?.querySelector('[type="submit"]'),surface=document.body.dataset.surface||'mobile';let busy=false;
  const setMessage=(text,state='')=>{if(message){message.textContent=text||'';message.className=`auth-message${state?` ${state}`:''}`;}};
  const setBusy=v=>{busy=v;if(submit)submit.disabled=v;for(const input of form?.querySelectorAll('input')||[])input.disabled=v;if(toggle)toggle.disabled=v;};
  const loadApi=()=>new Promise((resolve,reject)=>{if(window.MOLApi)return resolve(window.MOLApi);const s=document.createElement('script');s.src='../shared/api.js';s.onload=()=>resolve(window.MOLApi);s.onerror=()=>reject(new Error('Nie udało się załadować klienta API V2.'));document.head.append(s);});
  toggle?.addEventListener('click',()=>{const reveal=password.type==='password';password.type=reveal?'text':'password';toggle.textContent=reveal?'Ukryj':'Pokaż';toggle.setAttribute('aria-pressed',String(reveal));});
  const redirectFor=role=>location.replace(`./index.html?role=${encodeURIComponent(String(role||'').toUpperCase())}`),reason=new URLSearchParams(location.search).get('reason');
  if(reason==='session')setMessage('Sesja wygasła lub została zakończona. Zaloguj się ponownie.','is-error');if(reason==='worker_web')setMessage('Konto WORKER nie ma dostępu do panelu WWW.','is-error');
  form?.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const data=new FormData(form),username=String(data.get('username')||'').trim(),secret=String(data.get('password')||'');if(!username||!secret)return setMessage('Wpisz login i hasło.','is-error');setBusy(true);setMessage('Logowanie…');try{const api=await loadApi(),sess=await api.login(username,secret),role=String(sess?.user?.role||'').toUpperCase();if(surface==='web'&&role==='WORKER'){try{await api.logout({clearOnFailure:true});}catch{api.clearToken();}setMessage('Konto WORKER nie ma dostępu do panelu WWW.','is-error');return;}setMessage('Logowanie potwierdzone. Otwieram aplikację…','is-success');redirectFor(role);}catch(error){setMessage(error.message||'Logowanie nie powiodło się.','is-error');}finally{if(password)password.value='';setBusy(false);}});
  (async()=>{try{const api=await loadApi();if(!api.getToken())return;setBusy(true);setMessage('Sprawdzanie istniejącej sesji…');const sess=await api.requireSession({surface});if(sess){setMessage('Sesja aktywna. Otwieram aplikację…','is-success');redirectFor(sess.user.role);}}catch(error){if(error.status===403&&surface==='web')setMessage('Konto WORKER nie ma dostępu do panelu WWW.','is-error');else if(error.status===401)setMessage('Sesja wygasła. Zaloguj się ponownie.','is-error');else setMessage(error.message||'Nie udało się sprawdzić sesji.','is-error');try{window.MOLApi?.clearToken();}catch{}}finally{setBusy(false);}})();
})();
